import sst
import os
script_path = os.path.dirname(os.path.abspath(__file__))
sst.setProgramOption('timebase', '1s')


Albuquerque_ABQ = sst.Component('Albuquerque_ABQ', 'AirportSim.Airport')
Albuquerque_ABQ.addParams({
	'name' : 'Albuquerque_ABQ',
	'num_connectors' : 29,
	'num_planes' : 87
})



Altanta_ATL = sst.Component('Altanta_ATL', 'AirportSim.Airport')
Altanta_ATL.addParams({
	'name' : 'Altanta_ATL',
	'num_connectors' : 29,
	'num_planes' : 87
})



Baltimore_Washington_BWI = sst.Component('Baltimore_Washington_BWI', 'AirportSim.Airport')
Baltimore_Washington_BWI.addParams({
	'name' : 'Baltimore_Washington_BWI',
	'num_connectors' : 29,
	'num_planes' : 87
})



Boston_BOS = sst.Component('Boston_BOS', 'AirportSim.Airport')
Boston_BOS.addParams({
	'name' : 'Boston_BOS',
	'num_connectors' : 29,
	'num_planes' : 87
})



Charlotte_Douglas_CLT = sst.Component('Charlotte_Douglas_CLT', 'AirportSim.Airport')
Charlotte_Douglas_CLT.addParams({
	'name' : 'Charlotte_Douglas_CLT',
	'num_connectors' : 29,
	'num_planes' : 87
})



Chicago_ORD = sst.Component('Chicago_ORD', 'AirportSim.Airport')
Chicago_ORD.addParams({
	'name' : 'Chicago_ORD',
	'num_connectors' : 29,
	'num_planes' : 87
})



Chicago_MDW = sst.Component('Chicago_MDW', 'AirportSim.Airport')
Chicago_MDW.addParams({
	'name' : 'Chicago_MDW',
	'num_connectors' : 29,
	'num_planes' : 87
})



Cincinnati_Northern_Ketucky_CVG = sst.Component('Cincinnati_Northern_Ketucky_CVG', 'AirportSim.Airport')
Cincinnati_Northern_Ketucky_CVG.addParams({
	'name' : 'Cincinnati_Northern_Ketucky_CVG',
	'num_connectors' : 29,
	'num_planes' : 87
})



Denver_DEN = sst.Component('Denver_DEN', 'AirportSim.Airport')
Denver_DEN.addParams({
	'name' : 'Denver_DEN',
	'num_connectors' : 29,
	'num_planes' : 87
})



Dallas_DTW = sst.Component('Dallas_DTW', 'AirportSim.Airport')
Dallas_DTW.addParams({
	'name' : 'Dallas_DTW',
	'num_connectors' : 29,
	'num_planes' : 87
})



Dulles_IAD = sst.Component('Dulles_IAD', 'AirportSim.Airport')
Dulles_IAD.addParams({
	'name' : 'Dulles_IAD',
	'num_connectors' : 29,
	'num_planes' : 87
})



Eppley_OMA = sst.Component('Eppley_OMA', 'AirportSim.Airport')
Eppley_OMA.addParams({
	'name' : 'Eppley_OMA',
	'num_connectors' : 29,
	'num_planes' : 87
})



George_Bush_IAH = sst.Component('George_Bush_IAH', 'AirportSim.Airport')
George_Bush_IAH.addParams({
	'name' : 'George_Bush_IAH',
	'num_connectors' : 29,
	'num_planes' : 87
})



Harry_Reid_LAS = sst.Component('Harry_Reid_LAS', 'AirportSim.Airport')
Harry_Reid_LAS.addParams({
	'name' : 'Harry_Reid_LAS',
	'num_connectors' : 29,
	'num_planes' : 87
})



Indianapolis_IND = sst.Component('Indianapolis_IND', 'AirportSim.Airport')
Indianapolis_IND.addParams({
	'name' : 'Indianapolis_IND',
	'num_connectors' : 29,
	'num_planes' : 87
})



John_Wayne_SNA = sst.Component('John_Wayne_SNA', 'AirportSim.Airport')
John_Wayne_SNA.addParams({
	'name' : 'John_Wayne_SNA',
	'num_connectors' : 29,
	'num_planes' : 87
})



Minneapolis_MSP = sst.Component('Minneapolis_MSP', 'AirportSim.Airport')
Minneapolis_MSP.addParams({
	'name' : 'Minneapolis_MSP',
	'num_connectors' : 29,
	'num_planes' : 87
})



Milwaukee_MKE = sst.Component('Milwaukee_MKE', 'AirportSim.Airport')
Milwaukee_MKE.addParams({
	'name' : 'Milwaukee_MKE',
	'num_connectors' : 29,
	'num_planes' : 87
})



Newark_Liberty_EWR = sst.Component('Newark_Liberty_EWR', 'AirportSim.Airport')
Newark_Liberty_EWR.addParams({
	'name' : 'Newark_Liberty_EWR',
	'num_connectors' : 29,
	'num_planes' : 87
})



Philadelphia_PHL = sst.Component('Philadelphia_PHL', 'AirportSim.Airport')
Philadelphia_PHL.addParams({
	'name' : 'Philadelphia_PHL',
	'num_connectors' : 29,
	'num_planes' : 87
})



Phoenix_PHX = sst.Component('Phoenix_PHX', 'AirportSim.Airport')
Phoenix_PHX.addParams({
	'name' : 'Phoenix_PHX',
	'num_connectors' : 29,
	'num_planes' : 87
})



Portland_PDX = sst.Component('Portland_PDX', 'AirportSim.Airport')
Portland_PDX.addParams({
	'name' : 'Portland_PDX',
	'num_connectors' : 29,
	'num_planes' : 87
})



Los_Angeles_LAX = sst.Component('Los_Angeles_LAX', 'AirportSim.Airport')
Los_Angeles_LAX.addParams({
	'name' : 'Los_Angeles_LAX',
	'num_connectors' : 29,
	'num_planes' : 87
})



New_York_LGA = sst.Component('New_York_LGA', 'AirportSim.Airport')
New_York_LGA.addParams({
	'name' : 'New_York_LGA',
	'num_connectors' : 29,
	'num_planes' : 87
})



New_York_JFK = sst.Component('New_York_JFK', 'AirportSim.Airport')
New_York_JFK.addParams({
	'name' : 'New_York_JFK',
	'num_connectors' : 29,
	'num_planes' : 87
})



Salt_Lake_City_SLC = sst.Component('Salt_Lake_City_SLC', 'AirportSim.Airport')
Salt_Lake_City_SLC.addParams({
	'name' : 'Salt_Lake_City_SLC',
	'num_connectors' : 29,
	'num_planes' : 87
})



San_Diego_SAN = sst.Component('San_Diego_SAN', 'AirportSim.Airport')
San_Diego_SAN.addParams({
	'name' : 'San_Diego_SAN',
	'num_connectors' : 29,
	'num_planes' : 87
})



San_Francisco_SFO = sst.Component('San_Francisco_SFO', 'AirportSim.Airport')
San_Francisco_SFO.addParams({
	'name' : 'San_Francisco_SFO',
	'num_connectors' : 29,
	'num_planes' : 87
})



Seattle_Tacoma_SEA = sst.Component('Seattle_Tacoma_SEA', 'AirportSim.Airport')
Seattle_Tacoma_SEA.addParams({
	'name' : 'Seattle_Tacoma_SEA',
	'num_connectors' : 29,
	'num_planes' : 87
})



Tampa_TPA = sst.Component('Tampa_TPA', 'AirportSim.Airport')
Tampa_TPA.addParams({
	'name' : 'Tampa_TPA',
	'num_connectors' : 29,
	'num_planes' : 87
})



Albuquerque_ABQ_Altanta_ATL = sst.Link('Albuquerque_ABQ_Altanta_ATL')
Albuquerque_ABQ_Altanta_ATL.connect((Albuquerque_ABQ, 'airport_connector_0', '12s'), (Altanta_ATL, 'airport_connector_0', '12s'))
Albuquerque_ABQ_Baltimore_Washington_BWI = sst.Link('Albuquerque_ABQ_Baltimore_Washington_BWI')
Albuquerque_ABQ_Baltimore_Washington_BWI.connect((Albuquerque_ABQ, 'airport_connector_1', '16s'), (Baltimore_Washington_BWI, 'airport_connector_0', '16s'))
Albuquerque_ABQ_Boston_BOS = sst.Link('Albuquerque_ABQ_Boston_BOS')
Albuquerque_ABQ_Boston_BOS.connect((Albuquerque_ABQ, 'airport_connector_2', '19s'), (Boston_BOS, 'airport_connector_0', '19s'))
Albuquerque_ABQ_Charlotte_Douglas_CLT = sst.Link('Albuquerque_ABQ_Charlotte_Douglas_CLT')
Albuquerque_ABQ_Charlotte_Douglas_CLT.connect((Albuquerque_ABQ, 'airport_connector_3', '14s'), (Charlotte_Douglas_CLT, 'airport_connector_0', '14s'))
Albuquerque_ABQ_Chicago_ORD = sst.Link('Albuquerque_ABQ_Chicago_ORD')
Albuquerque_ABQ_Chicago_ORD.connect((Albuquerque_ABQ, 'airport_connector_4', '11s'), (Chicago_ORD, 'airport_connector_0', '11s'))
Albuquerque_ABQ_Chicago_MDW = sst.Link('Albuquerque_ABQ_Chicago_MDW')
Albuquerque_ABQ_Chicago_MDW.connect((Albuquerque_ABQ, 'airport_connector_5', '11s'), (Chicago_MDW, 'airport_connector_0', '11s'))
Albuquerque_ABQ_Cincinnati_Northern_Ketucky_CVG = sst.Link('Albuquerque_ABQ_Cincinnati_Northern_Ketucky_CVG')
Albuquerque_ABQ_Cincinnati_Northern_Ketucky_CVG.connect((Albuquerque_ABQ, 'airport_connector_6', '12s'), (Cincinnati_Northern_Ketucky_CVG, 'airport_connector_0', '12s'))
Albuquerque_ABQ_Denver_DEN = sst.Link('Albuquerque_ABQ_Denver_DEN')
Albuquerque_ABQ_Denver_DEN.connect((Albuquerque_ABQ, 'airport_connector_7', '13s'), (Denver_DEN, 'airport_connector_0', '13s'))
Albuquerque_ABQ_Dallas_DTW = sst.Link('Albuquerque_ABQ_Dallas_DTW')
Albuquerque_ABQ_Dallas_DTW.connect((Albuquerque_ABQ, 'airport_connector_8', '5s'), (Dallas_DTW, 'airport_connector_0', '5s'))
Albuquerque_ABQ_Dulles_IAD = sst.Link('Albuquerque_ABQ_Dulles_IAD')
Albuquerque_ABQ_Dulles_IAD.connect((Albuquerque_ABQ, 'airport_connector_9', '16s'), (Dulles_IAD, 'airport_connector_0', '16s'))
Albuquerque_ABQ_Eppley_OMA = sst.Link('Albuquerque_ABQ_Eppley_OMA')
Albuquerque_ABQ_Eppley_OMA.connect((Albuquerque_ABQ, 'airport_connector_10', '7s'), (Eppley_OMA, 'airport_connector_0', '7s'))
Albuquerque_ABQ_George_Bush_IAH = sst.Link('Albuquerque_ABQ_George_Bush_IAH')
Albuquerque_ABQ_George_Bush_IAH.connect((Albuquerque_ABQ, 'airport_connector_11', '7s'), (George_Bush_IAH, 'airport_connector_0', '7s'))
Albuquerque_ABQ_Harry_Reid_LAS = sst.Link('Albuquerque_ABQ_Harry_Reid_LAS')
Albuquerque_ABQ_Harry_Reid_LAS.connect((Albuquerque_ABQ, 'airport_connector_12', '4s'), (Harry_Reid_LAS, 'airport_connector_0', '4s'))
Albuquerque_ABQ_Indianapolis_IND = sst.Link('Albuquerque_ABQ_Indianapolis_IND')
Albuquerque_ABQ_Indianapolis_IND.connect((Albuquerque_ABQ, 'airport_connector_13', '11s'), (Indianapolis_IND, 'airport_connector_0', '11s'))
Albuquerque_ABQ_John_Wayne_SNA = sst.Link('Albuquerque_ABQ_John_Wayne_SNA')
Albuquerque_ABQ_John_Wayne_SNA.connect((Albuquerque_ABQ, 'airport_connector_14', '6s'), (John_Wayne_SNA, 'airport_connector_0', '6s'))
Albuquerque_ABQ_Minneapolis_MSP = sst.Link('Albuquerque_ABQ_Minneapolis_MSP')
Albuquerque_ABQ_Minneapolis_MSP.connect((Albuquerque_ABQ, 'airport_connector_15', '9s'), (Minneapolis_MSP, 'airport_connector_0', '9s'))
Albuquerque_ABQ_Milwaukee_MKE = sst.Link('Albuquerque_ABQ_Milwaukee_MKE')
Albuquerque_ABQ_Milwaukee_MKE.connect((Albuquerque_ABQ, 'airport_connector_16', '11s'), (Milwaukee_MKE, 'airport_connector_0', '11s'))
Albuquerque_ABQ_Newark_Liberty_EWR = sst.Link('Albuquerque_ABQ_Newark_Liberty_EWR')
Albuquerque_ABQ_Newark_Liberty_EWR.connect((Albuquerque_ABQ, 'airport_connector_17', '18s'), (Newark_Liberty_EWR, 'airport_connector_0', '18s'))
Albuquerque_ABQ_Philadelphia_PHL = sst.Link('Albuquerque_ABQ_Philadelphia_PHL')
Albuquerque_ABQ_Philadelphia_PHL.connect((Albuquerque_ABQ, 'airport_connector_18', '17s'), (Philadelphia_PHL, 'airport_connector_0', '17s'))
Albuquerque_ABQ_Phoenix_PHX = sst.Link('Albuquerque_ABQ_Phoenix_PHX')
Albuquerque_ABQ_Phoenix_PHX.connect((Albuquerque_ABQ, 'airport_connector_19', '3s'), (Phoenix_PHX, 'airport_connector_0', '3s'))
Albuquerque_ABQ_Portland_PDX = sst.Link('Albuquerque_ABQ_Portland_PDX')
Albuquerque_ABQ_Portland_PDX.connect((Albuquerque_ABQ, 'airport_connector_20', '11s'), (Portland_PDX, 'airport_connector_0', '11s'))
Albuquerque_ABQ_Los_Angeles_LAX = sst.Link('Albuquerque_ABQ_Los_Angeles_LAX')
Albuquerque_ABQ_Los_Angeles_LAX.connect((Albuquerque_ABQ, 'airport_connector_21', '6s'), (Los_Angeles_LAX, 'airport_connector_0', '6s'))
Albuquerque_ABQ_New_York_LGA = sst.Link('Albuquerque_ABQ_New_York_LGA')
Albuquerque_ABQ_New_York_LGA.connect((Albuquerque_ABQ, 'airport_connector_22', '18s'), (New_York_LGA, 'airport_connector_0', '18s'))
Albuquerque_ABQ_New_York_JFK = sst.Link('Albuquerque_ABQ_New_York_JFK')
Albuquerque_ABQ_New_York_JFK.connect((Albuquerque_ABQ, 'airport_connector_23', '18s'), (New_York_JFK, 'airport_connector_0', '18s'))
Albuquerque_ABQ_Salt_Lake_City_SLC = sst.Link('Albuquerque_ABQ_Salt_Lake_City_SLC')
Albuquerque_ABQ_Salt_Lake_City_SLC.connect((Albuquerque_ABQ, 'airport_connector_24', '4s'), (Salt_Lake_City_SLC, 'airport_connector_0', '4s'))
Albuquerque_ABQ_San_Diego_SAN = sst.Link('Albuquerque_ABQ_San_Diego_SAN')
Albuquerque_ABQ_San_Diego_SAN.connect((Albuquerque_ABQ, 'airport_connector_25', '6s'), (San_Diego_SAN, 'airport_connector_0', '6s'))
Albuquerque_ABQ_San_Francisco_SFO = sst.Link('Albuquerque_ABQ_San_Francisco_SFO')
Albuquerque_ABQ_San_Francisco_SFO.connect((Albuquerque_ABQ, 'airport_connector_26', '8s'), (San_Francisco_SFO, 'airport_connector_0', '8s'))
Albuquerque_ABQ_Seattle_Tacoma_SEA = sst.Link('Albuquerque_ABQ_Seattle_Tacoma_SEA')
Albuquerque_ABQ_Seattle_Tacoma_SEA.connect((Albuquerque_ABQ, 'airport_connector_27', '11s'), (Seattle_Tacoma_SEA, 'airport_connector_0', '11s'))
Albuquerque_ABQ_Tampa_TPA = sst.Link('Albuquerque_ABQ_Tampa_TPA')
Albuquerque_ABQ_Tampa_TPA.connect((Albuquerque_ABQ, 'airport_connector_28', '14s'), (Tampa_TPA, 'airport_connector_0', '14s'))
Altanta_ATL_Baltimore_Washington_BWI = sst.Link('Altanta_ATL_Baltimore_Washington_BWI')
Altanta_ATL_Baltimore_Washington_BWI.connect((Altanta_ATL, 'airport_connector_1', '5s'), (Baltimore_Washington_BWI, 'airport_connector_1', '5s'))
Altanta_ATL_Boston_BOS = sst.Link('Altanta_ATL_Boston_BOS')
Altanta_ATL_Boston_BOS.connect((Altanta_ATL, 'airport_connector_2', '9s'), (Boston_BOS, 'airport_connector_1', '9s'))
Altanta_ATL_Charlotte_Douglas_CLT = sst.Link('Altanta_ATL_Charlotte_Douglas_CLT')
Altanta_ATL_Charlotte_Douglas_CLT.connect((Altanta_ATL, 'airport_connector_3', '2s'), (Charlotte_Douglas_CLT, 'airport_connector_1', '2s'))
Altanta_ATL_Chicago_ORD = sst.Link('Altanta_ATL_Chicago_ORD')
Altanta_ATL_Chicago_ORD.connect((Altanta_ATL, 'airport_connector_4', '6s'), (Chicago_ORD, 'airport_connector_1', '6s'))
Altanta_ATL_Chicago_MDW = sst.Link('Altanta_ATL_Chicago_MDW')
Altanta_ATL_Chicago_MDW.connect((Altanta_ATL, 'airport_connector_5', '5s'), (Chicago_MDW, 'airport_connector_1', '5s'))
Altanta_ATL_Cincinnati_Northern_Ketucky_CVG = sst.Link('Altanta_ATL_Cincinnati_Northern_Ketucky_CVG')
Altanta_ATL_Cincinnati_Northern_Ketucky_CVG.connect((Altanta_ATL, 'airport_connector_6', '3s'), (Cincinnati_Northern_Ketucky_CVG, 'airport_connector_1', '3s'))
Altanta_ATL_Denver_DEN = sst.Link('Altanta_ATL_Denver_DEN')
Altanta_ATL_Denver_DEN.connect((Altanta_ATL, 'airport_connector_7', '5s'), (Denver_DEN, 'airport_connector_1', '5s'))
Altanta_ATL_Dallas_DTW = sst.Link('Altanta_ATL_Dallas_DTW')
Altanta_ATL_Dallas_DTW.connect((Altanta_ATL, 'airport_connector_8', '7s'), (Dallas_DTW, 'airport_connector_1', '7s'))
Altanta_ATL_Dulles_IAD = sst.Link('Altanta_ATL_Dulles_IAD')
Altanta_ATL_Dulles_IAD.connect((Altanta_ATL, 'airport_connector_9', '5s'), (Dulles_IAD, 'airport_connector_1', '5s'))
Altanta_ATL_Eppley_OMA = sst.Link('Altanta_ATL_Eppley_OMA')
Altanta_ATL_Eppley_OMA.connect((Altanta_ATL, 'airport_connector_10', '8s'), (Eppley_OMA, 'airport_connector_1', '8s'))
Altanta_ATL_George_Bush_IAH = sst.Link('Altanta_ATL_George_Bush_IAH')
Altanta_ATL_George_Bush_IAH.connect((Altanta_ATL, 'airport_connector_11', '6s'), (George_Bush_IAH, 'airport_connector_1', '6s'))
Altanta_ATL_Harry_Reid_LAS = sst.Link('Altanta_ATL_Harry_Reid_LAS')
Altanta_ATL_Harry_Reid_LAS.connect((Altanta_ATL, 'airport_connector_12', '17s'), (Harry_Reid_LAS, 'airport_connector_1', '17s'))
Altanta_ATL_Indianapolis_IND = sst.Link('Altanta_ATL_Indianapolis_IND')
Altanta_ATL_Indianapolis_IND.connect((Altanta_ATL, 'airport_connector_13', '4s'), (Indianapolis_IND, 'airport_connector_1', '4s'))
Altanta_ATL_John_Wayne_SNA = sst.Link('Altanta_ATL_John_Wayne_SNA')
Altanta_ATL_John_Wayne_SNA.connect((Altanta_ATL, 'airport_connector_14', '19s'), (John_Wayne_SNA, 'airport_connector_1', '19s'))
Altanta_ATL_Minneapolis_MSP = sst.Link('Altanta_ATL_Minneapolis_MSP')
Altanta_ATL_Minneapolis_MSP.connect((Altanta_ATL, 'airport_connector_15', '9s'), (Minneapolis_MSP, 'airport_connector_1', '9s'))
Altanta_ATL_Milwaukee_MKE = sst.Link('Altanta_ATL_Milwaukee_MKE')
Altanta_ATL_Milwaukee_MKE.connect((Altanta_ATL, 'airport_connector_16', '6s'), (Milwaukee_MKE, 'airport_connector_1', '6s'))
Altanta_ATL_Newark_Liberty_EWR = sst.Link('Altanta_ATL_Newark_Liberty_EWR')
Altanta_ATL_Newark_Liberty_EWR.connect((Altanta_ATL, 'airport_connector_17', '7s'), (Newark_Liberty_EWR, 'airport_connector_1', '7s'))
Altanta_ATL_Philadelphia_PHL = sst.Link('Altanta_ATL_Philadelphia_PHL')
Altanta_ATL_Philadelphia_PHL.connect((Altanta_ATL, 'airport_connector_18', '6s'), (Philadelphia_PHL, 'airport_connector_1', '6s'))
Altanta_ATL_Phoenix_PHX = sst.Link('Altanta_ATL_Phoenix_PHX')
Altanta_ATL_Phoenix_PHX.connect((Altanta_ATL, 'airport_connector_19', '15s'), (Phoenix_PHX, 'airport_connector_1', '15s'))
Altanta_ATL_Portland_PDX = sst.Link('Altanta_ATL_Portland_PDX')
Altanta_ATL_Portland_PDX.connect((Altanta_ATL, 'airport_connector_20', '21s'), (Portland_PDX, 'airport_connector_1', '21s'))
Altanta_ATL_Los_Angeles_LAX = sst.Link('Altanta_ATL_Los_Angeles_LAX')
Altanta_ATL_Los_Angeles_LAX.connect((Altanta_ATL, 'airport_connector_21', '19s'), (Los_Angeles_LAX, 'airport_connector_1', '19s'))
Altanta_ATL_New_York_LGA = sst.Link('Altanta_ATL_New_York_LGA')
Altanta_ATL_New_York_LGA.connect((Altanta_ATL, 'airport_connector_22', '7s'), (New_York_LGA, 'airport_connector_1', '7s'))
Altanta_ATL_New_York_JFK = sst.Link('Altanta_ATL_New_York_JFK')
Altanta_ATL_New_York_JFK.connect((Altanta_ATL, 'airport_connector_23', '7s'), (New_York_JFK, 'airport_connector_1', '7s'))
Altanta_ATL_Salt_Lake_City_SLC = sst.Link('Altanta_ATL_Salt_Lake_City_SLC')
Altanta_ATL_Salt_Lake_City_SLC.connect((Altanta_ATL, 'airport_connector_24', '15s'), (Salt_Lake_City_SLC, 'airport_connector_1', '15s'))
Altanta_ATL_San_Diego_SAN = sst.Link('Altanta_ATL_San_Diego_SAN')
Altanta_ATL_San_Diego_SAN.connect((Altanta_ATL, 'airport_connector_25', '18s'), (San_Diego_SAN, 'airport_connector_1', '18s'))
Altanta_ATL_San_Francisco_SFO = sst.Link('Altanta_ATL_San_Francisco_SFO')
Altanta_ATL_San_Francisco_SFO.connect((Altanta_ATL, 'airport_connector_26', '21s'), (San_Francisco_SFO, 'airport_connector_1', '21s'))
Altanta_ATL_Seattle_Tacoma_SEA = sst.Link('Altanta_ATL_Seattle_Tacoma_SEA')
Altanta_ATL_Seattle_Tacoma_SEA.connect((Altanta_ATL, 'airport_connector_27', '21s'), (Seattle_Tacoma_SEA, 'airport_connector_1', '21s'))
Altanta_ATL_Tampa_TPA = sst.Link('Altanta_ATL_Tampa_TPA')
Altanta_ATL_Tampa_TPA.connect((Altanta_ATL, 'airport_connector_28', '4s'), (Tampa_TPA, 'airport_connector_1', '4s'))
Baltimore_Washington_BWI_Boston_BOS = sst.Link('Baltimore_Washington_BWI_Boston_BOS')
Baltimore_Washington_BWI_Boston_BOS.connect((Baltimore_Washington_BWI, 'airport_connector_2', '3s'), (Boston_BOS, 'airport_connector_2', '3s'))
Baltimore_Washington_BWI_Charlotte_Douglas_CLT = sst.Link('Baltimore_Washington_BWI_Charlotte_Douglas_CLT')
Baltimore_Washington_BWI_Charlotte_Douglas_CLT.connect((Baltimore_Washington_BWI, 'airport_connector_3', '3s'), (Charlotte_Douglas_CLT, 'airport_connector_2', '3s'))
Baltimore_Washington_BWI_Chicago_ORD = sst.Link('Baltimore_Washington_BWI_Chicago_ORD')
Baltimore_Washington_BWI_Chicago_ORD.connect((Baltimore_Washington_BWI, 'airport_connector_4', '6s'), (Chicago_ORD, 'airport_connector_2', '6s'))
Baltimore_Washington_BWI_Chicago_MDW = sst.Link('Baltimore_Washington_BWI_Chicago_MDW')
Baltimore_Washington_BWI_Chicago_MDW.connect((Baltimore_Washington_BWI, 'airport_connector_5', '6s'), (Chicago_MDW, 'airport_connector_2', '6s'))
Baltimore_Washington_BWI_Cincinnati_Northern_Ketucky_CVG = sst.Link('Baltimore_Washington_BWI_Cincinnati_Northern_Ketucky_CVG')
Baltimore_Washington_BWI_Cincinnati_Northern_Ketucky_CVG.connect((Baltimore_Washington_BWI, 'airport_connector_6', '4s'), (Cincinnati_Northern_Ketucky_CVG, 'airport_connector_2', '4s'))
Baltimore_Washington_BWI_Denver_DEN = sst.Link('Baltimore_Washington_BWI_Denver_DEN')
Baltimore_Washington_BWI_Denver_DEN.connect((Baltimore_Washington_BWI, 'airport_connector_7', '4s'), (Denver_DEN, 'airport_connector_2', '4s'))
Baltimore_Washington_BWI_Dallas_DTW = sst.Link('Baltimore_Washington_BWI_Dallas_DTW')
Baltimore_Washington_BWI_Dallas_DTW.connect((Baltimore_Washington_BWI, 'airport_connector_8', '12s'), (Dallas_DTW, 'airport_connector_2', '12s'))
Baltimore_Washington_BWI_Dulles_IAD = sst.Link('Baltimore_Washington_BWI_Dulles_IAD')
Baltimore_Washington_BWI_Dulles_IAD.connect((Baltimore_Washington_BWI, 'airport_connector_9', '1s'), (Dulles_IAD, 'airport_connector_2', '1s'))
Baltimore_Washington_BWI_Eppley_OMA = sst.Link('Baltimore_Washington_BWI_Eppley_OMA')
Baltimore_Washington_BWI_Eppley_OMA.connect((Baltimore_Washington_BWI, 'airport_connector_10', '10s'), (Eppley_OMA, 'airport_connector_2', '10s'))
Baltimore_Washington_BWI_George_Bush_IAH = sst.Link('Baltimore_Washington_BWI_George_Bush_IAH')
Baltimore_Washington_BWI_George_Bush_IAH.connect((Baltimore_Washington_BWI, 'airport_connector_11', '12s'), (George_Bush_IAH, 'airport_connector_2', '12s'))
Baltimore_Washington_BWI_Harry_Reid_LAS = sst.Link('Baltimore_Washington_BWI_Harry_Reid_LAS')
Baltimore_Washington_BWI_Harry_Reid_LAS.connect((Baltimore_Washington_BWI, 'airport_connector_12', '21s'), (Harry_Reid_LAS, 'airport_connector_2', '21s'))
Baltimore_Washington_BWI_Indianapolis_IND = sst.Link('Baltimore_Washington_BWI_Indianapolis_IND')
Baltimore_Washington_BWI_Indianapolis_IND.connect((Baltimore_Washington_BWI, 'airport_connector_13', '5s'), (Indianapolis_IND, 'airport_connector_2', '5s'))
Baltimore_Washington_BWI_John_Wayne_SNA = sst.Link('Baltimore_Washington_BWI_John_Wayne_SNA')
Baltimore_Washington_BWI_John_Wayne_SNA.connect((Baltimore_Washington_BWI, 'airport_connector_14', '23s'), (John_Wayne_SNA, 'airport_connector_2', '23s'))
Baltimore_Washington_BWI_Minneapolis_MSP = sst.Link('Baltimore_Washington_BWI_Minneapolis_MSP')
Baltimore_Washington_BWI_Minneapolis_MSP.connect((Baltimore_Washington_BWI, 'airport_connector_15', '9s'), (Minneapolis_MSP, 'airport_connector_2', '9s'))
Baltimore_Washington_BWI_Milwaukee_MKE = sst.Link('Baltimore_Washington_BWI_Milwaukee_MKE')
Baltimore_Washington_BWI_Milwaukee_MKE.connect((Baltimore_Washington_BWI, 'airport_connector_16', '6s'), (Milwaukee_MKE, 'airport_connector_2', '6s'))
Baltimore_Washington_BWI_Newark_Liberty_EWR = sst.Link('Baltimore_Washington_BWI_Newark_Liberty_EWR')
Baltimore_Washington_BWI_Newark_Liberty_EWR.connect((Baltimore_Washington_BWI, 'airport_connector_17', '1s'), (Newark_Liberty_EWR, 'airport_connector_2', '1s'))
Baltimore_Washington_BWI_Philadelphia_PHL = sst.Link('Baltimore_Washington_BWI_Philadelphia_PHL')
Baltimore_Washington_BWI_Philadelphia_PHL.connect((Baltimore_Washington_BWI, 'airport_connector_18', '1s'), (Philadelphia_PHL, 'airport_connector_2', '1s'))
Baltimore_Washington_BWI_Phoenix_PHX = sst.Link('Baltimore_Washington_BWI_Phoenix_PHX')
Baltimore_Washington_BWI_Phoenix_PHX.connect((Baltimore_Washington_BWI, 'airport_connector_19', '19s'), (Phoenix_PHX, 'airport_connector_2', '19s'))
Baltimore_Washington_BWI_Portland_PDX = sst.Link('Baltimore_Washington_BWI_Portland_PDX')
Baltimore_Washington_BWI_Portland_PDX.connect((Baltimore_Washington_BWI, 'airport_connector_20', '23s'), (Portland_PDX, 'airport_connector_2', '23s'))
Baltimore_Washington_BWI_Los_Angeles_LAX = sst.Link('Baltimore_Washington_BWI_Los_Angeles_LAX')
Baltimore_Washington_BWI_Los_Angeles_LAX.connect((Baltimore_Washington_BWI, 'airport_connector_21', '23s'), (Los_Angeles_LAX, 'airport_connector_2', '23s'))
Baltimore_Washington_BWI_New_York_LGA = sst.Link('Baltimore_Washington_BWI_New_York_LGA')
Baltimore_Washington_BWI_New_York_LGA.connect((Baltimore_Washington_BWI, 'airport_connector_22', '1s'), (New_York_LGA, 'airport_connector_2', '1s'))
Baltimore_Washington_BWI_New_York_JFK = sst.Link('Baltimore_Washington_BWI_New_York_JFK')
Baltimore_Washington_BWI_New_York_JFK.connect((Baltimore_Washington_BWI, 'airport_connector_23', '1s'), (New_York_JFK, 'airport_connector_2', '1s'))
Baltimore_Washington_BWI_Salt_Lake_City_SLC = sst.Link('Baltimore_Washington_BWI_Salt_Lake_City_SLC')
Baltimore_Washington_BWI_Salt_Lake_City_SLC.connect((Baltimore_Washington_BWI, 'airport_connector_24', '18s'), (Salt_Lake_City_SLC, 'airport_connector_2', '18s'))
Baltimore_Washington_BWI_San_Diego_SAN = sst.Link('Baltimore_Washington_BWI_San_Diego_SAN')
Baltimore_Washington_BWI_San_Diego_SAN.connect((Baltimore_Washington_BWI, 'airport_connector_25', '22s'), (San_Diego_SAN, 'airport_connector_2', '22s'))
Baltimore_Washington_BWI_San_Francisco_SFO = sst.Link('Baltimore_Washington_BWI_San_Francisco_SFO')
Baltimore_Washington_BWI_San_Francisco_SFO.connect((Baltimore_Washington_BWI, 'airport_connector_26', '24s'), (San_Francisco_SFO, 'airport_connector_2', '24s'))
Baltimore_Washington_BWI_Seattle_Tacoma_SEA = sst.Link('Baltimore_Washington_BWI_Seattle_Tacoma_SEA')
Baltimore_Washington_BWI_Seattle_Tacoma_SEA.connect((Baltimore_Washington_BWI, 'airport_connector_27', '23s'), (Seattle_Tacoma_SEA, 'airport_connector_2', '23s'))
Baltimore_Washington_BWI_Tampa_TPA = sst.Link('Baltimore_Washington_BWI_Tampa_TPA')
Baltimore_Washington_BWI_Tampa_TPA.connect((Baltimore_Washington_BWI, 'airport_connector_28', '8s'), (Tampa_TPA, 'airport_connector_2', '8s'))
Boston_BOS_Charlotte_Douglas_CLT = sst.Link('Boston_BOS_Charlotte_Douglas_CLT')
Boston_BOS_Charlotte_Douglas_CLT.connect((Boston_BOS, 'airport_connector_3', '7s'), (Charlotte_Douglas_CLT, 'airport_connector_3', '7s'))
Boston_BOS_Chicago_ORD = sst.Link('Boston_BOS_Chicago_ORD')
Boston_BOS_Chicago_ORD.connect((Boston_BOS, 'airport_connector_4', '8s'), (Chicago_ORD, 'airport_connector_3', '8s'))
Boston_BOS_Chicago_MDW = sst.Link('Boston_BOS_Chicago_MDW')
Boston_BOS_Chicago_MDW.connect((Boston_BOS, 'airport_connector_5', '8s'), (Chicago_MDW, 'airport_connector_3', '8s'))
Boston_BOS_Cincinnati_Northern_Ketucky_CVG = sst.Link('Boston_BOS_Cincinnati_Northern_Ketucky_CVG')
Boston_BOS_Cincinnati_Northern_Ketucky_CVG.connect((Boston_BOS, 'airport_connector_6', '7s'), (Cincinnati_Northern_Ketucky_CVG, 'airport_connector_3', '7s'))
Boston_BOS_Denver_DEN = sst.Link('Boston_BOS_Denver_DEN')
Boston_BOS_Denver_DEN.connect((Boston_BOS, 'airport_connector_7', '6s'), (Denver_DEN, 'airport_connector_3', '6s'))
Boston_BOS_Dallas_DTW = sst.Link('Boston_BOS_Dallas_DTW')
Boston_BOS_Dallas_DTW.connect((Boston_BOS, 'airport_connector_8', '15s'), (Dallas_DTW, 'airport_connector_3', '15s'))
Boston_BOS_Dulles_IAD = sst.Link('Boston_BOS_Dulles_IAD')
Boston_BOS_Dulles_IAD.connect((Boston_BOS, 'airport_connector_9', '4s'), (Dulles_IAD, 'airport_connector_3', '4s'))
Boston_BOS_Eppley_OMA = sst.Link('Boston_BOS_Eppley_OMA')
Boston_BOS_Eppley_OMA.connect((Boston_BOS, 'airport_connector_10', '12s'), (Eppley_OMA, 'airport_connector_3', '12s'))
Boston_BOS_George_Bush_IAH = sst.Link('Boston_BOS_George_Bush_IAH')
Boston_BOS_George_Bush_IAH.connect((Boston_BOS, 'airport_connector_11', '15s'), (George_Bush_IAH, 'airport_connector_3', '15s'))
Boston_BOS_Harry_Reid_LAS = sst.Link('Boston_BOS_Harry_Reid_LAS')
Boston_BOS_Harry_Reid_LAS.connect((Boston_BOS, 'airport_connector_12', '23s'), (Harry_Reid_LAS, 'airport_connector_3', '23s'))
Boston_BOS_Indianapolis_IND = sst.Link('Boston_BOS_Indianapolis_IND')
Boston_BOS_Indianapolis_IND.connect((Boston_BOS, 'airport_connector_13', '8s'), (Indianapolis_IND, 'airport_connector_3', '8s'))
Boston_BOS_John_Wayne_SNA = sst.Link('Boston_BOS_John_Wayne_SNA')
Boston_BOS_John_Wayne_SNA.connect((Boston_BOS, 'airport_connector_14', '25s'), (John_Wayne_SNA, 'airport_connector_3', '25s'))
Boston_BOS_Minneapolis_MSP = sst.Link('Boston_BOS_Minneapolis_MSP')
Boston_BOS_Minneapolis_MSP.connect((Boston_BOS, 'airport_connector_15', '11s'), (Minneapolis_MSP, 'airport_connector_3', '11s'))
Boston_BOS_Milwaukee_MKE = sst.Link('Boston_BOS_Milwaukee_MKE')
Boston_BOS_Milwaukee_MKE.connect((Boston_BOS, 'airport_connector_16', '8s'), (Milwaukee_MKE, 'airport_connector_3', '8s'))
Boston_BOS_Newark_Liberty_EWR = sst.Link('Boston_BOS_Newark_Liberty_EWR')
Boston_BOS_Newark_Liberty_EWR.connect((Boston_BOS, 'airport_connector_17', '2s'), (Newark_Liberty_EWR, 'airport_connector_3', '2s'))
Boston_BOS_Philadelphia_PHL = sst.Link('Boston_BOS_Philadelphia_PHL')
Boston_BOS_Philadelphia_PHL.connect((Boston_BOS, 'airport_connector_18', '2s'), (Philadelphia_PHL, 'airport_connector_3', '2s'))
Boston_BOS_Phoenix_PHX = sst.Link('Boston_BOS_Phoenix_PHX')
Boston_BOS_Phoenix_PHX.connect((Boston_BOS, 'airport_connector_19', '22s'), (Phoenix_PHX, 'airport_connector_3', '22s'))
Boston_BOS_Portland_PDX = sst.Link('Boston_BOS_Portland_PDX')
Boston_BOS_Portland_PDX.connect((Boston_BOS, 'airport_connector_20', '25s'), (Portland_PDX, 'airport_connector_3', '25s'))
Boston_BOS_Los_Angeles_LAX = sst.Link('Boston_BOS_Los_Angeles_LAX')
Boston_BOS_Los_Angeles_LAX.connect((Boston_BOS, 'airport_connector_21', '26s'), (Los_Angeles_LAX, 'airport_connector_3', '26s'))
Boston_BOS_New_York_LGA = sst.Link('Boston_BOS_New_York_LGA')
Boston_BOS_New_York_LGA.connect((Boston_BOS, 'airport_connector_22', '1s'), (New_York_LGA, 'airport_connector_3', '1s'))
Boston_BOS_New_York_JFK = sst.Link('Boston_BOS_New_York_JFK')
Boston_BOS_New_York_JFK.connect((Boston_BOS, 'airport_connector_23', '1s'), (New_York_JFK, 'airport_connector_3', '1s'))
Boston_BOS_Salt_Lake_City_SLC = sst.Link('Boston_BOS_Salt_Lake_City_SLC')
Boston_BOS_Salt_Lake_City_SLC.connect((Boston_BOS, 'airport_connector_24', '21s'), (Salt_Lake_City_SLC, 'airport_connector_3', '21s'))
Boston_BOS_San_Diego_SAN = sst.Link('Boston_BOS_San_Diego_SAN')
Boston_BOS_San_Diego_SAN.connect((Boston_BOS, 'airport_connector_25', '25s'), (San_Diego_SAN, 'airport_connector_3', '25s'))
Boston_BOS_San_Francisco_SFO = sst.Link('Boston_BOS_San_Francisco_SFO')
Boston_BOS_San_Francisco_SFO.connect((Boston_BOS, 'airport_connector_26', '27s'), (San_Francisco_SFO, 'airport_connector_3', '27s'))
Boston_BOS_Seattle_Tacoma_SEA = sst.Link('Boston_BOS_Seattle_Tacoma_SEA')
Boston_BOS_Seattle_Tacoma_SEA.connect((Boston_BOS, 'airport_connector_27', '24s'), (Seattle_Tacoma_SEA, 'airport_connector_3', '24s'))
Boston_BOS_Tampa_TPA = sst.Link('Boston_BOS_Tampa_TPA')
Boston_BOS_Tampa_TPA.connect((Boston_BOS, 'airport_connector_28', '11s'), (Tampa_TPA, 'airport_connector_3', '11s'))
Charlotte_Douglas_CLT_Chicago_ORD = sst.Link('Charlotte_Douglas_CLT_Chicago_ORD')
Charlotte_Douglas_CLT_Chicago_ORD.connect((Charlotte_Douglas_CLT, 'airport_connector_4', '5s'), (Chicago_ORD, 'airport_connector_4', '5s'))
Charlotte_Douglas_CLT_Chicago_MDW = sst.Link('Charlotte_Douglas_CLT_Chicago_MDW')
Charlotte_Douglas_CLT_Chicago_MDW.connect((Charlotte_Douglas_CLT, 'airport_connector_5', '5s'), (Chicago_MDW, 'airport_connector_4', '5s'))
Charlotte_Douglas_CLT_Cincinnati_Northern_Ketucky_CVG = sst.Link('Charlotte_Douglas_CLT_Cincinnati_Northern_Ketucky_CVG')
Charlotte_Douglas_CLT_Cincinnati_Northern_Ketucky_CVG.connect((Charlotte_Douglas_CLT, 'airport_connector_6', '3s'), (Cincinnati_Northern_Ketucky_CVG, 'airport_connector_4', '3s'))
Charlotte_Douglas_CLT_Denver_DEN = sst.Link('Charlotte_Douglas_CLT_Denver_DEN')
Charlotte_Douglas_CLT_Denver_DEN.connect((Charlotte_Douglas_CLT, 'airport_connector_7', '4s'), (Denver_DEN, 'airport_connector_4', '4s'))
Charlotte_Douglas_CLT_Dallas_DTW = sst.Link('Charlotte_Douglas_CLT_Dallas_DTW')
Charlotte_Douglas_CLT_Dallas_DTW.connect((Charlotte_Douglas_CLT, 'airport_connector_8', '9s'), (Dallas_DTW, 'airport_connector_4', '9s'))
Charlotte_Douglas_CLT_Dulles_IAD = sst.Link('Charlotte_Douglas_CLT_Dulles_IAD')
Charlotte_Douglas_CLT_Dulles_IAD.connect((Charlotte_Douglas_CLT, 'airport_connector_9', '3s'), (Dulles_IAD, 'airport_connector_4', '3s'))
Charlotte_Douglas_CLT_Eppley_OMA = sst.Link('Charlotte_Douglas_CLT_Eppley_OMA')
Charlotte_Douglas_CLT_Eppley_OMA.connect((Charlotte_Douglas_CLT, 'airport_connector_10', '9s'), (Eppley_OMA, 'airport_connector_4', '9s'))
Charlotte_Douglas_CLT_George_Bush_IAH = sst.Link('Charlotte_Douglas_CLT_George_Bush_IAH')
Charlotte_Douglas_CLT_George_Bush_IAH.connect((Charlotte_Douglas_CLT, 'airport_connector_11', '9s'), (George_Bush_IAH, 'airport_connector_4', '9s'))
Charlotte_Douglas_CLT_Harry_Reid_LAS = sst.Link('Charlotte_Douglas_CLT_Harry_Reid_LAS')
Charlotte_Douglas_CLT_Harry_Reid_LAS.connect((Charlotte_Douglas_CLT, 'airport_connector_12', '19s'), (Harry_Reid_LAS, 'airport_connector_4', '19s'))
Charlotte_Douglas_CLT_Indianapolis_IND = sst.Link('Charlotte_Douglas_CLT_Indianapolis_IND')
Charlotte_Douglas_CLT_Indianapolis_IND.connect((Charlotte_Douglas_CLT, 'airport_connector_13', '4s'), (Indianapolis_IND, 'airport_connector_4', '4s'))
Charlotte_Douglas_CLT_John_Wayne_SNA = sst.Link('Charlotte_Douglas_CLT_John_Wayne_SNA')
Charlotte_Douglas_CLT_John_Wayne_SNA.connect((Charlotte_Douglas_CLT, 'airport_connector_14', '20s'), (John_Wayne_SNA, 'airport_connector_4', '20s'))
Charlotte_Douglas_CLT_Minneapolis_MSP = sst.Link('Charlotte_Douglas_CLT_Minneapolis_MSP')
Charlotte_Douglas_CLT_Minneapolis_MSP.connect((Charlotte_Douglas_CLT, 'airport_connector_15', '9s'), (Minneapolis_MSP, 'airport_connector_4', '9s'))
Charlotte_Douglas_CLT_Milwaukee_MKE = sst.Link('Charlotte_Douglas_CLT_Milwaukee_MKE')
Charlotte_Douglas_CLT_Milwaukee_MKE.connect((Charlotte_Douglas_CLT, 'airport_connector_16', '6s'), (Milwaukee_MKE, 'airport_connector_4', '6s'))
Charlotte_Douglas_CLT_Newark_Liberty_EWR = sst.Link('Charlotte_Douglas_CLT_Newark_Liberty_EWR')
Charlotte_Douglas_CLT_Newark_Liberty_EWR.connect((Charlotte_Douglas_CLT, 'airport_connector_17', '5s'), (Newark_Liberty_EWR, 'airport_connector_4', '5s'))
Charlotte_Douglas_CLT_Philadelphia_PHL = sst.Link('Charlotte_Douglas_CLT_Philadelphia_PHL')
Charlotte_Douglas_CLT_Philadelphia_PHL.connect((Charlotte_Douglas_CLT, 'airport_connector_18', '4s'), (Philadelphia_PHL, 'airport_connector_4', '4s'))
Charlotte_Douglas_CLT_Phoenix_PHX = sst.Link('Charlotte_Douglas_CLT_Phoenix_PHX')
Charlotte_Douglas_CLT_Phoenix_PHX.connect((Charlotte_Douglas_CLT, 'airport_connector_19', '17s'), (Phoenix_PHX, 'airport_connector_4', '17s'))
Charlotte_Douglas_CLT_Portland_PDX = sst.Link('Charlotte_Douglas_CLT_Portland_PDX')
Charlotte_Douglas_CLT_Portland_PDX.connect((Charlotte_Douglas_CLT, 'airport_connector_20', '22s'), (Portland_PDX, 'airport_connector_4', '22s'))
Charlotte_Douglas_CLT_Los_Angeles_LAX = sst.Link('Charlotte_Douglas_CLT_Los_Angeles_LAX')
Charlotte_Douglas_CLT_Los_Angeles_LAX.connect((Charlotte_Douglas_CLT, 'airport_connector_21', '21s'), (Los_Angeles_LAX, 'airport_connector_4', '21s'))
Charlotte_Douglas_CLT_New_York_LGA = sst.Link('Charlotte_Douglas_CLT_New_York_LGA')
Charlotte_Douglas_CLT_New_York_LGA.connect((Charlotte_Douglas_CLT, 'airport_connector_22', '5s'), (New_York_LGA, 'airport_connector_4', '5s'))
Charlotte_Douglas_CLT_New_York_JFK = sst.Link('Charlotte_Douglas_CLT_New_York_JFK')
Charlotte_Douglas_CLT_New_York_JFK.connect((Charlotte_Douglas_CLT, 'airport_connector_23', '5s'), (New_York_JFK, 'airport_connector_4', '5s'))
Charlotte_Douglas_CLT_Salt_Lake_City_SLC = sst.Link('Charlotte_Douglas_CLT_Salt_Lake_City_SLC')
Charlotte_Douglas_CLT_Salt_Lake_City_SLC.connect((Charlotte_Douglas_CLT, 'airport_connector_24', '17s'), (Salt_Lake_City_SLC, 'airport_connector_4', '17s'))
Charlotte_Douglas_CLT_San_Diego_SAN = sst.Link('Charlotte_Douglas_CLT_San_Diego_SAN')
Charlotte_Douglas_CLT_San_Diego_SAN.connect((Charlotte_Douglas_CLT, 'airport_connector_25', '20s'), (San_Diego_SAN, 'airport_connector_4', '20s'))
Charlotte_Douglas_CLT_San_Francisco_SFO = sst.Link('Charlotte_Douglas_CLT_San_Francisco_SFO')
Charlotte_Douglas_CLT_San_Francisco_SFO.connect((Charlotte_Douglas_CLT, 'airport_connector_26', '22s'), (San_Francisco_SFO, 'airport_connector_4', '22s'))
Charlotte_Douglas_CLT_Seattle_Tacoma_SEA = sst.Link('Charlotte_Douglas_CLT_Seattle_Tacoma_SEA')
Charlotte_Douglas_CLT_Seattle_Tacoma_SEA.connect((Charlotte_Douglas_CLT, 'airport_connector_27', '22s'), (Seattle_Tacoma_SEA, 'airport_connector_4', '22s'))
Charlotte_Douglas_CLT_Tampa_TPA = sst.Link('Charlotte_Douglas_CLT_Tampa_TPA')
Charlotte_Douglas_CLT_Tampa_TPA.connect((Charlotte_Douglas_CLT, 'airport_connector_28', '5s'), (Tampa_TPA, 'airport_connector_4', '5s'))
Chicago_ORD_Chicago_MDW = sst.Link('Chicago_ORD_Chicago_MDW')
Chicago_ORD_Chicago_MDW.connect((Chicago_ORD, 'airport_connector_5', '1s'), (Chicago_MDW, 'airport_connector_5', '1s'))
Chicago_ORD_Cincinnati_Northern_Ketucky_CVG = sst.Link('Chicago_ORD_Cincinnati_Northern_Ketucky_CVG')
Chicago_ORD_Cincinnati_Northern_Ketucky_CVG.connect((Chicago_ORD, 'airport_connector_6', '2s'), (Cincinnati_Northern_Ketucky_CVG, 'airport_connector_5', '2s'))
Chicago_ORD_Denver_DEN = sst.Link('Chicago_ORD_Denver_DEN')
Chicago_ORD_Denver_DEN.connect((Chicago_ORD, 'airport_connector_7', '2s'), (Denver_DEN, 'airport_connector_5', '2s'))
Chicago_ORD_Dallas_DTW = sst.Link('Chicago_ORD_Dallas_DTW')
Chicago_ORD_Dallas_DTW.connect((Chicago_ORD, 'airport_connector_8', '8s'), (Dallas_DTW, 'airport_connector_5', '8s'))
Chicago_ORD_Dulles_IAD = sst.Link('Chicago_ORD_Dulles_IAD')
Chicago_ORD_Dulles_IAD.connect((Chicago_ORD, 'airport_connector_9', '5s'), (Dulles_IAD, 'airport_connector_5', '5s'))
Chicago_ORD_Eppley_OMA = sst.Link('Chicago_ORD_Eppley_OMA')
Chicago_ORD_Eppley_OMA.connect((Chicago_ORD, 'airport_connector_10', '4s'), (Eppley_OMA, 'airport_connector_5', '4s'))
Chicago_ORD_George_Bush_IAH = sst.Link('Chicago_ORD_George_Bush_IAH')
Chicago_ORD_George_Bush_IAH.connect((Chicago_ORD, 'airport_connector_11', '9s'), (George_Bush_IAH, 'airport_connector_5', '9s'))
Chicago_ORD_Harry_Reid_LAS = sst.Link('Chicago_ORD_Harry_Reid_LAS')
Chicago_ORD_Harry_Reid_LAS.connect((Chicago_ORD, 'airport_connector_12', '15s'), (Harry_Reid_LAS, 'airport_connector_5', '15s'))
Chicago_ORD_Indianapolis_IND = sst.Link('Chicago_ORD_Indianapolis_IND')
Chicago_ORD_Indianapolis_IND.connect((Chicago_ORD, 'airport_connector_13', '1s'), (Indianapolis_IND, 'airport_connector_5', '1s'))
Chicago_ORD_John_Wayne_SNA = sst.Link('Chicago_ORD_John_Wayne_SNA')
Chicago_ORD_John_Wayne_SNA.connect((Chicago_ORD, 'airport_connector_14', '17s'), (John_Wayne_SNA, 'airport_connector_5', '17s'))
Chicago_ORD_Minneapolis_MSP = sst.Link('Chicago_ORD_Minneapolis_MSP')
Chicago_ORD_Minneapolis_MSP.connect((Chicago_ORD, 'airport_connector_15', '3s'), (Minneapolis_MSP, 'airport_connector_5', '3s'))
Chicago_ORD_Milwaukee_MKE = sst.Link('Chicago_ORD_Milwaukee_MKE')
Chicago_ORD_Milwaukee_MKE.connect((Chicago_ORD, 'airport_connector_16', '1s'), (Milwaukee_MKE, 'airport_connector_5', '1s'))
Chicago_ORD_Newark_Liberty_EWR = sst.Link('Chicago_ORD_Newark_Liberty_EWR')
Chicago_ORD_Newark_Liberty_EWR.connect((Chicago_ORD, 'airport_connector_17', '7s'), (Newark_Liberty_EWR, 'airport_connector_5', '7s'))
Chicago_ORD_Philadelphia_PHL = sst.Link('Chicago_ORD_Philadelphia_PHL')
Chicago_ORD_Philadelphia_PHL.connect((Chicago_ORD, 'airport_connector_18', '6s'), (Philadelphia_PHL, 'airport_connector_5', '6s'))
Chicago_ORD_Phoenix_PHX = sst.Link('Chicago_ORD_Phoenix_PHX')
Chicago_ORD_Phoenix_PHX.connect((Chicago_ORD, 'airport_connector_19', '14s'), (Phoenix_PHX, 'airport_connector_5', '14s'))
Chicago_ORD_Portland_PDX = sst.Link('Chicago_ORD_Portland_PDX')
Chicago_ORD_Portland_PDX.connect((Chicago_ORD, 'airport_connector_20', '17s'), (Portland_PDX, 'airport_connector_5', '17s'))
Chicago_ORD_Los_Angeles_LAX = sst.Link('Chicago_ORD_Los_Angeles_LAX')
Chicago_ORD_Los_Angeles_LAX.connect((Chicago_ORD, 'airport_connector_21', '17s'), (Los_Angeles_LAX, 'airport_connector_5', '17s'))
Chicago_ORD_New_York_LGA = sst.Link('Chicago_ORD_New_York_LGA')
Chicago_ORD_New_York_LGA.connect((Chicago_ORD, 'airport_connector_22', '7s'), (New_York_LGA, 'airport_connector_5', '7s'))
Chicago_ORD_New_York_JFK = sst.Link('Chicago_ORD_New_York_JFK')
Chicago_ORD_New_York_JFK.connect((Chicago_ORD, 'airport_connector_23', '7s'), (New_York_JFK, 'airport_connector_5', '7s'))
Chicago_ORD_Salt_Lake_City_SLC = sst.Link('Chicago_ORD_Salt_Lake_City_SLC')
Chicago_ORD_Salt_Lake_City_SLC.connect((Chicago_ORD, 'airport_connector_24', '12s'), (Salt_Lake_City_SLC, 'airport_connector_5', '12s'))
Chicago_ORD_San_Diego_SAN = sst.Link('Chicago_ORD_San_Diego_SAN')
Chicago_ORD_San_Diego_SAN.connect((Chicago_ORD, 'airport_connector_25', '17s'), (San_Diego_SAN, 'airport_connector_5', '17s'))
Chicago_ORD_San_Francisco_SFO = sst.Link('Chicago_ORD_San_Francisco_SFO')
Chicago_ORD_San_Francisco_SFO.connect((Chicago_ORD, 'airport_connector_26', '18s'), (San_Francisco_SFO, 'airport_connector_5', '18s'))
Chicago_ORD_Seattle_Tacoma_SEA = sst.Link('Chicago_ORD_Seattle_Tacoma_SEA')
Chicago_ORD_Seattle_Tacoma_SEA.connect((Chicago_ORD, 'airport_connector_27', '17s'), (Seattle_Tacoma_SEA, 'airport_connector_5', '17s'))
Chicago_ORD_Tampa_TPA = sst.Link('Chicago_ORD_Tampa_TPA')
Chicago_ORD_Tampa_TPA.connect((Chicago_ORD, 'airport_connector_28', '10s'), (Tampa_TPA, 'airport_connector_5', '10s'))
Chicago_MDW_Cincinnati_Northern_Ketucky_CVG = sst.Link('Chicago_MDW_Cincinnati_Northern_Ketucky_CVG')
Chicago_MDW_Cincinnati_Northern_Ketucky_CVG.connect((Chicago_MDW, 'airport_connector_6', '2s'), (Cincinnati_Northern_Ketucky_CVG, 'airport_connector_6', '2s'))
Chicago_MDW_Denver_DEN = sst.Link('Chicago_MDW_Denver_DEN')
Chicago_MDW_Denver_DEN.connect((Chicago_MDW, 'airport_connector_7', '2s'), (Denver_DEN, 'airport_connector_6', '2s'))
Chicago_MDW_Dallas_DTW = sst.Link('Chicago_MDW_Dallas_DTW')
Chicago_MDW_Dallas_DTW.connect((Chicago_MDW, 'airport_connector_8', '7s'), (Dallas_DTW, 'airport_connector_6', '7s'))
Chicago_MDW_Dulles_IAD = sst.Link('Chicago_MDW_Dulles_IAD')
Chicago_MDW_Dulles_IAD.connect((Chicago_MDW, 'airport_connector_9', '5s'), (Dulles_IAD, 'airport_connector_6', '5s'))
Chicago_MDW_Eppley_OMA = sst.Link('Chicago_MDW_Eppley_OMA')
Chicago_MDW_Eppley_OMA.connect((Chicago_MDW, 'airport_connector_10', '4s'), (Eppley_OMA, 'airport_connector_6', '4s'))
Chicago_MDW_George_Bush_IAH = sst.Link('Chicago_MDW_George_Bush_IAH')
Chicago_MDW_George_Bush_IAH.connect((Chicago_MDW, 'airport_connector_11', '9s'), (George_Bush_IAH, 'airport_connector_6', '9s'))
Chicago_MDW_Harry_Reid_LAS = sst.Link('Chicago_MDW_Harry_Reid_LAS')
Chicago_MDW_Harry_Reid_LAS.connect((Chicago_MDW, 'airport_connector_12', '15s'), (Harry_Reid_LAS, 'airport_connector_6', '15s'))
Chicago_MDW_Indianapolis_IND = sst.Link('Chicago_MDW_Indianapolis_IND')
Chicago_MDW_Indianapolis_IND.connect((Chicago_MDW, 'airport_connector_13', '1s'), (Indianapolis_IND, 'airport_connector_6', '1s'))
Chicago_MDW_John_Wayne_SNA = sst.Link('Chicago_MDW_John_Wayne_SNA')
Chicago_MDW_John_Wayne_SNA.connect((Chicago_MDW, 'airport_connector_14', '17s'), (John_Wayne_SNA, 'airport_connector_6', '17s'))
Chicago_MDW_Minneapolis_MSP = sst.Link('Chicago_MDW_Minneapolis_MSP')
Chicago_MDW_Minneapolis_MSP.connect((Chicago_MDW, 'airport_connector_15', '3s'), (Minneapolis_MSP, 'airport_connector_6', '3s'))
Chicago_MDW_Milwaukee_MKE = sst.Link('Chicago_MDW_Milwaukee_MKE')
Chicago_MDW_Milwaukee_MKE.connect((Chicago_MDW, 'airport_connector_16', '1s'), (Milwaukee_MKE, 'airport_connector_6', '1s'))
Chicago_MDW_Newark_Liberty_EWR = sst.Link('Chicago_MDW_Newark_Liberty_EWR')
Chicago_MDW_Newark_Liberty_EWR.connect((Chicago_MDW, 'airport_connector_17', '7s'), (Newark_Liberty_EWR, 'airport_connector_6', '7s'))
Chicago_MDW_Philadelphia_PHL = sst.Link('Chicago_MDW_Philadelphia_PHL')
Chicago_MDW_Philadelphia_PHL.connect((Chicago_MDW, 'airport_connector_18', '6s'), (Philadelphia_PHL, 'airport_connector_6', '6s'))
Chicago_MDW_Phoenix_PHX = sst.Link('Chicago_MDW_Phoenix_PHX')
Chicago_MDW_Phoenix_PHX.connect((Chicago_MDW, 'airport_connector_19', '14s'), (Phoenix_PHX, 'airport_connector_6', '14s'))
Chicago_MDW_Portland_PDX = sst.Link('Chicago_MDW_Portland_PDX')
Chicago_MDW_Portland_PDX.connect((Chicago_MDW, 'airport_connector_20', '17s'), (Portland_PDX, 'airport_connector_6', '17s'))
Chicago_MDW_Los_Angeles_LAX = sst.Link('Chicago_MDW_Los_Angeles_LAX')
Chicago_MDW_Los_Angeles_LAX.connect((Chicago_MDW, 'airport_connector_21', '17s'), (Los_Angeles_LAX, 'airport_connector_6', '17s'))
Chicago_MDW_New_York_LGA = sst.Link('Chicago_MDW_New_York_LGA')
Chicago_MDW_New_York_LGA.connect((Chicago_MDW, 'airport_connector_22', '7s'), (New_York_LGA, 'airport_connector_6', '7s'))
Chicago_MDW_New_York_JFK = sst.Link('Chicago_MDW_New_York_JFK')
Chicago_MDW_New_York_JFK.connect((Chicago_MDW, 'airport_connector_23', '7s'), (New_York_JFK, 'airport_connector_6', '7s'))
Chicago_MDW_Salt_Lake_City_SLC = sst.Link('Chicago_MDW_Salt_Lake_City_SLC')
Chicago_MDW_Salt_Lake_City_SLC.connect((Chicago_MDW, 'airport_connector_24', '12s'), (Salt_Lake_City_SLC, 'airport_connector_6', '12s'))
Chicago_MDW_San_Diego_SAN = sst.Link('Chicago_MDW_San_Diego_SAN')
Chicago_MDW_San_Diego_SAN.connect((Chicago_MDW, 'airport_connector_25', '17s'), (San_Diego_SAN, 'airport_connector_6', '17s'))
Chicago_MDW_San_Francisco_SFO = sst.Link('Chicago_MDW_San_Francisco_SFO')
Chicago_MDW_San_Francisco_SFO.connect((Chicago_MDW, 'airport_connector_26', '18s'), (San_Francisco_SFO, 'airport_connector_6', '18s'))
Chicago_MDW_Seattle_Tacoma_SEA = sst.Link('Chicago_MDW_Seattle_Tacoma_SEA')
Chicago_MDW_Seattle_Tacoma_SEA.connect((Chicago_MDW, 'airport_connector_27', '17s'), (Seattle_Tacoma_SEA, 'airport_connector_6', '17s'))
Chicago_MDW_Tampa_TPA = sst.Link('Chicago_MDW_Tampa_TPA')
Chicago_MDW_Tampa_TPA.connect((Chicago_MDW, 'airport_connector_28', '9s'), (Tampa_TPA, 'airport_connector_6', '9s'))
Cincinnati_Northern_Ketucky_CVG_Denver_DEN = sst.Link('Cincinnati_Northern_Ketucky_CVG_Denver_DEN')
Cincinnati_Northern_Ketucky_CVG_Denver_DEN.connect((Cincinnati_Northern_Ketucky_CVG, 'airport_connector_7', '2s'), (Denver_DEN, 'airport_connector_7', '2s'))
Cincinnati_Northern_Ketucky_CVG_Dallas_DTW = sst.Link('Cincinnati_Northern_Ketucky_CVG_Dallas_DTW')
Cincinnati_Northern_Ketucky_CVG_Dallas_DTW.connect((Cincinnati_Northern_Ketucky_CVG, 'airport_connector_8', '8s'), (Dallas_DTW, 'airport_connector_7', '8s'))
Cincinnati_Northern_Ketucky_CVG_Dulles_IAD = sst.Link('Cincinnati_Northern_Ketucky_CVG_Dulles_IAD')
Cincinnati_Northern_Ketucky_CVG_Dulles_IAD.connect((Cincinnati_Northern_Ketucky_CVG, 'airport_connector_9', '3s'), (Dulles_IAD, 'airport_connector_7', '3s'))
Cincinnati_Northern_Ketucky_CVG_Eppley_OMA = sst.Link('Cincinnati_Northern_Ketucky_CVG_Eppley_OMA')
Cincinnati_Northern_Ketucky_CVG_Eppley_OMA.connect((Cincinnati_Northern_Ketucky_CVG, 'airport_connector_10', '6s'), (Eppley_OMA, 'airport_connector_7', '6s'))
Cincinnati_Northern_Ketucky_CVG_George_Bush_IAH = sst.Link('Cincinnati_Northern_Ketucky_CVG_George_Bush_IAH')
Cincinnati_Northern_Ketucky_CVG_George_Bush_IAH.connect((Cincinnati_Northern_Ketucky_CVG, 'airport_connector_11', '8s'), (George_Bush_IAH, 'airport_connector_7', '8s'))
Cincinnati_Northern_Ketucky_CVG_Harry_Reid_LAS = sst.Link('Cincinnati_Northern_Ketucky_CVG_Harry_Reid_LAS')
Cincinnati_Northern_Ketucky_CVG_Harry_Reid_LAS.connect((Cincinnati_Northern_Ketucky_CVG, 'airport_connector_12', '16s'), (Harry_Reid_LAS, 'airport_connector_7', '16s'))
Cincinnati_Northern_Ketucky_CVG_Indianapolis_IND = sst.Link('Cincinnati_Northern_Ketucky_CVG_Indianapolis_IND')
Cincinnati_Northern_Ketucky_CVG_Indianapolis_IND.connect((Cincinnati_Northern_Ketucky_CVG, 'airport_connector_13', '1s'), (Indianapolis_IND, 'airport_connector_7', '1s'))
Cincinnati_Northern_Ketucky_CVG_John_Wayne_SNA = sst.Link('Cincinnati_Northern_Ketucky_CVG_John_Wayne_SNA')
Cincinnati_Northern_Ketucky_CVG_John_Wayne_SNA.connect((Cincinnati_Northern_Ketucky_CVG, 'airport_connector_14', '18s'), (John_Wayne_SNA, 'airport_connector_7', '18s'))
Cincinnati_Northern_Ketucky_CVG_Minneapolis_MSP = sst.Link('Cincinnati_Northern_Ketucky_CVG_Minneapolis_MSP')
Cincinnati_Northern_Ketucky_CVG_Minneapolis_MSP.connect((Cincinnati_Northern_Ketucky_CVG, 'airport_connector_15', '5s'), (Minneapolis_MSP, 'airport_connector_7', '5s'))
Cincinnati_Northern_Ketucky_CVG_Milwaukee_MKE = sst.Link('Cincinnati_Northern_Ketucky_CVG_Milwaukee_MKE')
Cincinnati_Northern_Ketucky_CVG_Milwaukee_MKE.connect((Cincinnati_Northern_Ketucky_CVG, 'airport_connector_16', '3s'), (Milwaukee_MKE, 'airport_connector_7', '3s'))
Cincinnati_Northern_Ketucky_CVG_Newark_Liberty_EWR = sst.Link('Cincinnati_Northern_Ketucky_CVG_Newark_Liberty_EWR')
Cincinnati_Northern_Ketucky_CVG_Newark_Liberty_EWR.connect((Cincinnati_Northern_Ketucky_CVG, 'airport_connector_17', '5s'), (Newark_Liberty_EWR, 'airport_connector_7', '5s'))
Cincinnati_Northern_Ketucky_CVG_Philadelphia_PHL = sst.Link('Cincinnati_Northern_Ketucky_CVG_Philadelphia_PHL')
Cincinnati_Northern_Ketucky_CVG_Philadelphia_PHL.connect((Cincinnati_Northern_Ketucky_CVG, 'airport_connector_18', '5s'), (Philadelphia_PHL, 'airport_connector_7', '5s'))
Cincinnati_Northern_Ketucky_CVG_Phoenix_PHX = sst.Link('Cincinnati_Northern_Ketucky_CVG_Phoenix_PHX')
Cincinnati_Northern_Ketucky_CVG_Phoenix_PHX.connect((Cincinnati_Northern_Ketucky_CVG, 'airport_connector_19', '15s'), (Phoenix_PHX, 'airport_connector_7', '15s'))
Cincinnati_Northern_Ketucky_CVG_Portland_PDX = sst.Link('Cincinnati_Northern_Ketucky_CVG_Portland_PDX')
Cincinnati_Northern_Ketucky_CVG_Portland_PDX.connect((Cincinnati_Northern_Ketucky_CVG, 'airport_connector_20', '19s'), (Portland_PDX, 'airport_connector_7', '19s'))
Cincinnati_Northern_Ketucky_CVG_Los_Angeles_LAX = sst.Link('Cincinnati_Northern_Ketucky_CVG_Los_Angeles_LAX')
Cincinnati_Northern_Ketucky_CVG_Los_Angeles_LAX.connect((Cincinnati_Northern_Ketucky_CVG, 'airport_connector_21', '18s'), (Los_Angeles_LAX, 'airport_connector_7', '18s'))
Cincinnati_Northern_Ketucky_CVG_New_York_LGA = sst.Link('Cincinnati_Northern_Ketucky_CVG_New_York_LGA')
Cincinnati_Northern_Ketucky_CVG_New_York_LGA.connect((Cincinnati_Northern_Ketucky_CVG, 'airport_connector_22', '5s'), (New_York_LGA, 'airport_connector_7', '5s'))
Cincinnati_Northern_Ketucky_CVG_New_York_JFK = sst.Link('Cincinnati_Northern_Ketucky_CVG_New_York_JFK')
Cincinnati_Northern_Ketucky_CVG_New_York_JFK.connect((Cincinnati_Northern_Ketucky_CVG, 'airport_connector_23', '5s'), (New_York_JFK, 'airport_connector_7', '5s'))
Cincinnati_Northern_Ketucky_CVG_Salt_Lake_City_SLC = sst.Link('Cincinnati_Northern_Ketucky_CVG_Salt_Lake_City_SLC')
Cincinnati_Northern_Ketucky_CVG_Salt_Lake_City_SLC.connect((Cincinnati_Northern_Ketucky_CVG, 'airport_connector_24', '14s'), (Salt_Lake_City_SLC, 'airport_connector_7', '14s'))
Cincinnati_Northern_Ketucky_CVG_San_Diego_SAN = sst.Link('Cincinnati_Northern_Ketucky_CVG_San_Diego_SAN')
Cincinnati_Northern_Ketucky_CVG_San_Diego_SAN.connect((Cincinnati_Northern_Ketucky_CVG, 'airport_connector_25', '18s'), (San_Diego_SAN, 'airport_connector_7', '18s'))
Cincinnati_Northern_Ketucky_CVG_San_Francisco_SFO = sst.Link('Cincinnati_Northern_Ketucky_CVG_San_Francisco_SFO')
Cincinnati_Northern_Ketucky_CVG_San_Francisco_SFO.connect((Cincinnati_Northern_Ketucky_CVG, 'airport_connector_26', '20s'), (San_Francisco_SFO, 'airport_connector_7', '20s'))
Cincinnati_Northern_Ketucky_CVG_Seattle_Tacoma_SEA = sst.Link('Cincinnati_Northern_Ketucky_CVG_Seattle_Tacoma_SEA')
Cincinnati_Northern_Ketucky_CVG_Seattle_Tacoma_SEA.connect((Cincinnati_Northern_Ketucky_CVG, 'airport_connector_27', '19s'), (Seattle_Tacoma_SEA, 'airport_connector_7', '19s'))
Cincinnati_Northern_Ketucky_CVG_Tampa_TPA = sst.Link('Cincinnati_Northern_Ketucky_CVG_Tampa_TPA')
Cincinnati_Northern_Ketucky_CVG_Tampa_TPA.connect((Cincinnati_Northern_Ketucky_CVG, 'airport_connector_28', '7s'), (Tampa_TPA, 'airport_connector_7', '7s'))
Denver_DEN_Dallas_DTW = sst.Link('Denver_DEN_Dallas_DTW')
Denver_DEN_Dallas_DTW.connect((Denver_DEN, 'airport_connector_8', '9s'), (Dallas_DTW, 'airport_connector_8', '9s'))
Denver_DEN_Dulles_IAD = sst.Link('Denver_DEN_Dulles_IAD')
Denver_DEN_Dulles_IAD.connect((Denver_DEN, 'airport_connector_9', '3s'), (Dulles_IAD, 'airport_connector_8', '3s'))
Denver_DEN_Eppley_OMA = sst.Link('Denver_DEN_Eppley_OMA')
Denver_DEN_Eppley_OMA.connect((Denver_DEN, 'airport_connector_10', '6s'), (Eppley_OMA, 'airport_connector_8', '6s'))
Denver_DEN_George_Bush_IAH = sst.Link('Denver_DEN_George_Bush_IAH')
Denver_DEN_George_Bush_IAH.connect((Denver_DEN, 'airport_connector_11', '10s'), (George_Bush_IAH, 'airport_connector_8', '10s'))
Denver_DEN_Harry_Reid_LAS = sst.Link('Denver_DEN_Harry_Reid_LAS')
Denver_DEN_Harry_Reid_LAS.connect((Denver_DEN, 'airport_connector_12', '17s'), (Harry_Reid_LAS, 'airport_connector_8', '17s'))
Denver_DEN_Indianapolis_IND = sst.Link('Denver_DEN_Indianapolis_IND')
Denver_DEN_Indianapolis_IND.connect((Denver_DEN, 'airport_connector_13', '2s'), (Indianapolis_IND, 'airport_connector_8', '2s'))
Denver_DEN_John_Wayne_SNA = sst.Link('Denver_DEN_John_Wayne_SNA')
Denver_DEN_John_Wayne_SNA.connect((Denver_DEN, 'airport_connector_14', '19s'), (John_Wayne_SNA, 'airport_connector_8', '19s'))
Denver_DEN_Minneapolis_MSP = sst.Link('Denver_DEN_Minneapolis_MSP')
Denver_DEN_Minneapolis_MSP.connect((Denver_DEN, 'airport_connector_15', '5s'), (Minneapolis_MSP, 'airport_connector_8', '5s'))
Denver_DEN_Milwaukee_MKE = sst.Link('Denver_DEN_Milwaukee_MKE')
Denver_DEN_Milwaukee_MKE.connect((Denver_DEN, 'airport_connector_16', '2s'), (Milwaukee_MKE, 'airport_connector_8', '2s'))
Denver_DEN_Newark_Liberty_EWR = sst.Link('Denver_DEN_Newark_Liberty_EWR')
Denver_DEN_Newark_Liberty_EWR.connect((Denver_DEN, 'airport_connector_17', '4s'), (Newark_Liberty_EWR, 'airport_connector_8', '4s'))
Denver_DEN_Philadelphia_PHL = sst.Link('Denver_DEN_Philadelphia_PHL')
Denver_DEN_Philadelphia_PHL.connect((Denver_DEN, 'airport_connector_18', '4s'), (Philadelphia_PHL, 'airport_connector_8', '4s'))
Denver_DEN_Phoenix_PHX = sst.Link('Denver_DEN_Phoenix_PHX')
Denver_DEN_Phoenix_PHX.connect((Denver_DEN, 'airport_connector_19', '16s'), (Phoenix_PHX, 'airport_connector_8', '16s'))
Denver_DEN_Portland_PDX = sst.Link('Denver_DEN_Portland_PDX')
Denver_DEN_Portland_PDX.connect((Denver_DEN, 'airport_connector_20', '19s'), (Portland_PDX, 'airport_connector_8', '19s'))
Denver_DEN_Los_Angeles_LAX = sst.Link('Denver_DEN_Los_Angeles_LAX')
Denver_DEN_Los_Angeles_LAX.connect((Denver_DEN, 'airport_connector_21', '19s'), (Los_Angeles_LAX, 'airport_connector_8', '19s'))
Denver_DEN_New_York_LGA = sst.Link('Denver_DEN_New_York_LGA')
Denver_DEN_New_York_LGA.connect((Denver_DEN, 'airport_connector_22', '5s'), (New_York_LGA, 'airport_connector_8', '5s'))
Denver_DEN_New_York_JFK = sst.Link('Denver_DEN_New_York_JFK')
Denver_DEN_New_York_JFK.connect((Denver_DEN, 'airport_connector_23', '5s'), (New_York_JFK, 'airport_connector_8', '5s'))
Denver_DEN_Salt_Lake_City_SLC = sst.Link('Denver_DEN_Salt_Lake_City_SLC')
Denver_DEN_Salt_Lake_City_SLC.connect((Denver_DEN, 'airport_connector_24', '14s'), (Salt_Lake_City_SLC, 'airport_connector_8', '14s'))
Denver_DEN_San_Diego_SAN = sst.Link('Denver_DEN_San_Diego_SAN')
Denver_DEN_San_Diego_SAN.connect((Denver_DEN, 'airport_connector_25', '19s'), (San_Diego_SAN, 'airport_connector_8', '19s'))
Denver_DEN_San_Francisco_SFO = sst.Link('Denver_DEN_San_Francisco_SFO')
Denver_DEN_San_Francisco_SFO.connect((Denver_DEN, 'airport_connector_26', '20s'), (San_Francisco_SFO, 'airport_connector_8', '20s'))
Denver_DEN_Seattle_Tacoma_SEA = sst.Link('Denver_DEN_Seattle_Tacoma_SEA')
Denver_DEN_Seattle_Tacoma_SEA.connect((Denver_DEN, 'airport_connector_27', '19s'), (Seattle_Tacoma_SEA, 'airport_connector_8', '19s'))
Denver_DEN_Tampa_TPA = sst.Link('Denver_DEN_Tampa_TPA')
Denver_DEN_Tampa_TPA.connect((Denver_DEN, 'airport_connector_28', '9s'), (Tampa_TPA, 'airport_connector_8', '9s'))
Dallas_DTW_Dulles_IAD = sst.Link('Dallas_DTW_Dulles_IAD')
Dallas_DTW_Dulles_IAD.connect((Dallas_DTW, 'airport_connector_9', '11s'), (Dulles_IAD, 'airport_connector_9', '11s'))
Dallas_DTW_Eppley_OMA = sst.Link('Dallas_DTW_Eppley_OMA')
Dallas_DTW_Eppley_OMA.connect((Dallas_DTW, 'airport_connector_10', '5s'), (Eppley_OMA, 'airport_connector_9', '5s'))
Dallas_DTW_George_Bush_IAH = sst.Link('Dallas_DTW_George_Bush_IAH')
Dallas_DTW_George_Bush_IAH.connect((Dallas_DTW, 'airport_connector_11', '2s'), (George_Bush_IAH, 'airport_connector_9', '2s'))
Dallas_DTW_Harry_Reid_LAS = sst.Link('Dallas_DTW_Harry_Reid_LAS')
Dallas_DTW_Harry_Reid_LAS.connect((Dallas_DTW, 'airport_connector_12', '10s'), (Harry_Reid_LAS, 'airport_connector_9', '10s'))
Dallas_DTW_Indianapolis_IND = sst.Link('Dallas_DTW_Indianapolis_IND')
Dallas_DTW_Indianapolis_IND.connect((Dallas_DTW, 'airport_connector_13', '7s'), (Indianapolis_IND, 'airport_connector_9', '7s'))
Dallas_DTW_John_Wayne_SNA = sst.Link('Dallas_DTW_John_Wayne_SNA')
Dallas_DTW_John_Wayne_SNA.connect((Dallas_DTW, 'airport_connector_14', '12s'), (John_Wayne_SNA, 'airport_connector_9', '12s'))
Dallas_DTW_Minneapolis_MSP = sst.Link('Dallas_DTW_Minneapolis_MSP')
Dallas_DTW_Minneapolis_MSP.connect((Dallas_DTW, 'airport_connector_15', '8s'), (Minneapolis_MSP, 'airport_connector_9', '8s'))
Dallas_DTW_Milwaukee_MKE = sst.Link('Dallas_DTW_Milwaukee_MKE')
Dallas_DTW_Milwaukee_MKE.connect((Dallas_DTW, 'airport_connector_16', '8s'), (Milwaukee_MKE, 'airport_connector_9', '8s'))
Dallas_DTW_Newark_Liberty_EWR = sst.Link('Dallas_DTW_Newark_Liberty_EWR')
Dallas_DTW_Newark_Liberty_EWR.connect((Dallas_DTW, 'airport_connector_17', '13s'), (Newark_Liberty_EWR, 'airport_connector_9', '13s'))
Dallas_DTW_Philadelphia_PHL = sst.Link('Dallas_DTW_Philadelphia_PHL')
Dallas_DTW_Philadelphia_PHL.connect((Dallas_DTW, 'airport_connector_18', '13s'), (Philadelphia_PHL, 'airport_connector_9', '13s'))
Dallas_DTW_Phoenix_PHX = sst.Link('Dallas_DTW_Phoenix_PHX')
Dallas_DTW_Phoenix_PHX.connect((Dallas_DTW, 'airport_connector_19', '8s'), (Phoenix_PHX, 'airport_connector_9', '8s'))
Dallas_DTW_Portland_PDX = sst.Link('Dallas_DTW_Portland_PDX')
Dallas_DTW_Portland_PDX.connect((Dallas_DTW, 'airport_connector_20', '16s'), (Portland_PDX, 'airport_connector_9', '16s'))
Dallas_DTW_Los_Angeles_LAX = sst.Link('Dallas_DTW_Los_Angeles_LAX')
Dallas_DTW_Los_Angeles_LAX.connect((Dallas_DTW, 'airport_connector_21', '12s'), (Los_Angeles_LAX, 'airport_connector_9', '12s'))
Dallas_DTW_New_York_LGA = sst.Link('Dallas_DTW_New_York_LGA')
Dallas_DTW_New_York_LGA.connect((Dallas_DTW, 'airport_connector_22', '13s'), (New_York_LGA, 'airport_connector_9', '13s'))
Dallas_DTW_New_York_JFK = sst.Link('Dallas_DTW_New_York_JFK')
Dallas_DTW_New_York_JFK.connect((Dallas_DTW, 'airport_connector_23', '13s'), (New_York_JFK, 'airport_connector_9', '13s'))
Dallas_DTW_Salt_Lake_City_SLC = sst.Link('Dallas_DTW_Salt_Lake_City_SLC')
Dallas_DTW_Salt_Lake_City_SLC.connect((Dallas_DTW, 'airport_connector_24', '9s'), (Salt_Lake_City_SLC, 'airport_connector_9', '9s'))
Dallas_DTW_San_Diego_SAN = sst.Link('Dallas_DTW_San_Diego_SAN')
Dallas_DTW_San_Diego_SAN.connect((Dallas_DTW, 'airport_connector_25', '11s'), (San_Diego_SAN, 'airport_connector_9', '11s'))
Dallas_DTW_San_Francisco_SFO = sst.Link('Dallas_DTW_San_Francisco_SFO')
Dallas_DTW_San_Francisco_SFO.connect((Dallas_DTW, 'airport_connector_26', '14s'), (San_Francisco_SFO, 'airport_connector_9', '14s'))
Dallas_DTW_Seattle_Tacoma_SEA = sst.Link('Dallas_DTW_Seattle_Tacoma_SEA')
Dallas_DTW_Seattle_Tacoma_SEA.connect((Dallas_DTW, 'airport_connector_27', '16s'), (Seattle_Tacoma_SEA, 'airport_connector_9', '16s'))
Dallas_DTW_Tampa_TPA = sst.Link('Dallas_DTW_Tampa_TPA')
Dallas_DTW_Tampa_TPA.connect((Dallas_DTW, 'airport_connector_28', '9s'), (Tampa_TPA, 'airport_connector_9', '9s'))
Dulles_IAD_Eppley_OMA = sst.Link('Dulles_IAD_Eppley_OMA')
Dulles_IAD_Eppley_OMA.connect((Dulles_IAD, 'airport_connector_10', '9s'), (Eppley_OMA, 'airport_connector_10', '9s'))
Dulles_IAD_George_Bush_IAH = sst.Link('Dulles_IAD_George_Bush_IAH')
Dulles_IAD_George_Bush_IAH.connect((Dulles_IAD, 'airport_connector_11', '11s'), (George_Bush_IAH, 'airport_connector_10', '11s'))
Dulles_IAD_Harry_Reid_LAS = sst.Link('Dulles_IAD_Harry_Reid_LAS')
Dulles_IAD_Harry_Reid_LAS.connect((Dulles_IAD, 'airport_connector_12', '20s'), (Harry_Reid_LAS, 'airport_connector_10', '20s'))
Dulles_IAD_Indianapolis_IND = sst.Link('Dulles_IAD_Indianapolis_IND')
Dulles_IAD_Indianapolis_IND.connect((Dulles_IAD, 'airport_connector_13', '4s'), (Indianapolis_IND, 'airport_connector_10', '4s'))
Dulles_IAD_John_Wayne_SNA = sst.Link('Dulles_IAD_John_Wayne_SNA')
Dulles_IAD_John_Wayne_SNA.connect((Dulles_IAD, 'airport_connector_14', '22s'), (John_Wayne_SNA, 'airport_connector_10', '22s'))
Dulles_IAD_Minneapolis_MSP = sst.Link('Dulles_IAD_Minneapolis_MSP')
Dulles_IAD_Minneapolis_MSP.connect((Dulles_IAD, 'airport_connector_15', '9s'), (Minneapolis_MSP, 'airport_connector_10', '9s'))
Dulles_IAD_Milwaukee_MKE = sst.Link('Dulles_IAD_Milwaukee_MKE')
Dulles_IAD_Milwaukee_MKE.connect((Dulles_IAD, 'airport_connector_16', '6s'), (Milwaukee_MKE, 'airport_connector_10', '6s'))
Dulles_IAD_Newark_Liberty_EWR = sst.Link('Dulles_IAD_Newark_Liberty_EWR')
Dulles_IAD_Newark_Liberty_EWR.connect((Dulles_IAD, 'airport_connector_17', '2s'), (Newark_Liberty_EWR, 'airport_connector_10', '2s'))
Dulles_IAD_Philadelphia_PHL = sst.Link('Dulles_IAD_Philadelphia_PHL')
Dulles_IAD_Philadelphia_PHL.connect((Dulles_IAD, 'airport_connector_18', '1s'), (Philadelphia_PHL, 'airport_connector_10', '1s'))
Dulles_IAD_Phoenix_PHX = sst.Link('Dulles_IAD_Phoenix_PHX')
Dulles_IAD_Phoenix_PHX.connect((Dulles_IAD, 'airport_connector_19', '19s'), (Phoenix_PHX, 'airport_connector_10', '19s'))
Dulles_IAD_Portland_PDX = sst.Link('Dulles_IAD_Portland_PDX')
Dulles_IAD_Portland_PDX.connect((Dulles_IAD, 'airport_connector_20', '23s'), (Portland_PDX, 'airport_connector_10', '23s'))
Dulles_IAD_Los_Angeles_LAX = sst.Link('Dulles_IAD_Los_Angeles_LAX')
Dulles_IAD_Los_Angeles_LAX.connect((Dulles_IAD, 'airport_connector_21', '22s'), (Los_Angeles_LAX, 'airport_connector_10', '22s'))
Dulles_IAD_New_York_LGA = sst.Link('Dulles_IAD_New_York_LGA')
Dulles_IAD_New_York_LGA.connect((Dulles_IAD, 'airport_connector_22', '2s'), (New_York_LGA, 'airport_connector_10', '2s'))
Dulles_IAD_New_York_JFK = sst.Link('Dulles_IAD_New_York_JFK')
Dulles_IAD_New_York_JFK.connect((Dulles_IAD, 'airport_connector_23', '2s'), (New_York_JFK, 'airport_connector_10', '2s'))
Dulles_IAD_Salt_Lake_City_SLC = sst.Link('Dulles_IAD_Salt_Lake_City_SLC')
Dulles_IAD_Salt_Lake_City_SLC.connect((Dulles_IAD, 'airport_connector_24', '18s'), (Salt_Lake_City_SLC, 'airport_connector_10', '18s'))
Dulles_IAD_San_Diego_SAN = sst.Link('Dulles_IAD_San_Diego_SAN')
Dulles_IAD_San_Diego_SAN.connect((Dulles_IAD, 'airport_connector_25', '22s'), (San_Diego_SAN, 'airport_connector_10', '22s'))
Dulles_IAD_San_Francisco_SFO = sst.Link('Dulles_IAD_San_Francisco_SFO')
Dulles_IAD_San_Francisco_SFO.connect((Dulles_IAD, 'airport_connector_26', '24s'), (San_Francisco_SFO, 'airport_connector_10', '24s'))
Dulles_IAD_Seattle_Tacoma_SEA = sst.Link('Dulles_IAD_Seattle_Tacoma_SEA')
Dulles_IAD_Seattle_Tacoma_SEA.connect((Dulles_IAD, 'airport_connector_27', '23s'), (Seattle_Tacoma_SEA, 'airport_connector_10', '23s'))
Dulles_IAD_Tampa_TPA = sst.Link('Dulles_IAD_Tampa_TPA')
Dulles_IAD_Tampa_TPA.connect((Dulles_IAD, 'airport_connector_28', '8s'), (Tampa_TPA, 'airport_connector_10', '8s'))
Eppley_OMA_George_Bush_IAH = sst.Link('Eppley_OMA_George_Bush_IAH')
Eppley_OMA_George_Bush_IAH.connect((Eppley_OMA, 'airport_connector_11', '7s'), (George_Bush_IAH, 'airport_connector_11', '7s'))
Eppley_OMA_Harry_Reid_LAS = sst.Link('Eppley_OMA_Harry_Reid_LAS')
Eppley_OMA_Harry_Reid_LAS.connect((Eppley_OMA, 'airport_connector_12', '10s'), (Harry_Reid_LAS, 'airport_connector_11', '10s'))
Eppley_OMA_Indianapolis_IND = sst.Link('Eppley_OMA_Indianapolis_IND')
Eppley_OMA_Indianapolis_IND.connect((Eppley_OMA, 'airport_connector_13', '5s'), (Indianapolis_IND, 'airport_connector_11', '5s'))
Eppley_OMA_John_Wayne_SNA = sst.Link('Eppley_OMA_John_Wayne_SNA')
Eppley_OMA_John_Wayne_SNA.connect((Eppley_OMA, 'airport_connector_14', '13s'), (John_Wayne_SNA, 'airport_connector_11', '13s'))
Eppley_OMA_Minneapolis_MSP = sst.Link('Eppley_OMA_Minneapolis_MSP')
Eppley_OMA_Minneapolis_MSP.connect((Eppley_OMA, 'airport_connector_15', '2s'), (Minneapolis_MSP, 'airport_connector_11', '2s'))
Eppley_OMA_Milwaukee_MKE = sst.Link('Eppley_OMA_Milwaukee_MKE')
Eppley_OMA_Milwaukee_MKE.connect((Eppley_OMA, 'airport_connector_16', '4s'), (Milwaukee_MKE, 'airport_connector_11', '4s'))
Eppley_OMA_Newark_Liberty_EWR = sst.Link('Eppley_OMA_Newark_Liberty_EWR')
Eppley_OMA_Newark_Liberty_EWR.connect((Eppley_OMA, 'airport_connector_17', '11s'), (Newark_Liberty_EWR, 'airport_connector_11', '11s'))
Eppley_OMA_Philadelphia_PHL = sst.Link('Eppley_OMA_Philadelphia_PHL')
Eppley_OMA_Philadelphia_PHL.connect((Eppley_OMA, 'airport_connector_18', '10s'), (Philadelphia_PHL, 'airport_connector_11', '10s'))
Eppley_OMA_Phoenix_PHX = sst.Link('Eppley_OMA_Phoenix_PHX')
Eppley_OMA_Phoenix_PHX.connect((Eppley_OMA, 'airport_connector_19', '10s'), (Phoenix_PHX, 'airport_connector_11', '10s'))
Eppley_OMA_Portland_PDX = sst.Link('Eppley_OMA_Portland_PDX')
Eppley_OMA_Portland_PDX.connect((Eppley_OMA, 'airport_connector_20', '13s'), (Portland_PDX, 'airport_connector_11', '13s'))
Eppley_OMA_Los_Angeles_LAX = sst.Link('Eppley_OMA_Los_Angeles_LAX')
Eppley_OMA_Los_Angeles_LAX.connect((Eppley_OMA, 'airport_connector_21', '13s'), (Los_Angeles_LAX, 'airport_connector_11', '13s'))
Eppley_OMA_New_York_LGA = sst.Link('Eppley_OMA_New_York_LGA')
Eppley_OMA_New_York_LGA.connect((Eppley_OMA, 'airport_connector_22', '11s'), (New_York_LGA, 'airport_connector_11', '11s'))
Eppley_OMA_New_York_JFK = sst.Link('Eppley_OMA_New_York_JFK')
Eppley_OMA_New_York_JFK.connect((Eppley_OMA, 'airport_connector_23', '11s'), (New_York_JFK, 'airport_connector_11', '11s'))
Eppley_OMA_Salt_Lake_City_SLC = sst.Link('Eppley_OMA_Salt_Lake_City_SLC')
Eppley_OMA_Salt_Lake_City_SLC.connect((Eppley_OMA, 'airport_connector_24', '8s'), (Salt_Lake_City_SLC, 'airport_connector_11', '8s'))
Eppley_OMA_San_Diego_SAN = sst.Link('Eppley_OMA_San_Diego_SAN')
Eppley_OMA_San_Diego_SAN.connect((Eppley_OMA, 'airport_connector_25', '13s'), (San_Diego_SAN, 'airport_connector_11', '13s'))
Eppley_OMA_San_Francisco_SFO = sst.Link('Eppley_OMA_San_Francisco_SFO')
Eppley_OMA_San_Francisco_SFO.connect((Eppley_OMA, 'airport_connector_26', '14s'), (San_Francisco_SFO, 'airport_connector_11', '14s'))
Eppley_OMA_Seattle_Tacoma_SEA = sst.Link('Eppley_OMA_Seattle_Tacoma_SEA')
Eppley_OMA_Seattle_Tacoma_SEA.connect((Eppley_OMA, 'airport_connector_27', '13s'), (Seattle_Tacoma_SEA, 'airport_connector_11', '13s'))
Eppley_OMA_Tampa_TPA = sst.Link('Eppley_OMA_Tampa_TPA')
Eppley_OMA_Tampa_TPA.connect((Eppley_OMA, 'airport_connector_28', '11s'), (Tampa_TPA, 'airport_connector_11', '11s'))
George_Bush_IAH_Harry_Reid_LAS = sst.Link('George_Bush_IAH_Harry_Reid_LAS')
George_Bush_IAH_Harry_Reid_LAS.connect((George_Bush_IAH, 'airport_connector_12', '12s'), (Harry_Reid_LAS, 'airport_connector_12', '12s'))
George_Bush_IAH_Indianapolis_IND = sst.Link('George_Bush_IAH_Indianapolis_IND')
George_Bush_IAH_Indianapolis_IND.connect((George_Bush_IAH, 'airport_connector_13', '8s'), (Indianapolis_IND, 'airport_connector_12', '8s'))
George_Bush_IAH_John_Wayne_SNA = sst.Link('George_Bush_IAH_John_Wayne_SNA')
George_Bush_IAH_John_Wayne_SNA.connect((George_Bush_IAH, 'airport_connector_14', '13s'), (John_Wayne_SNA, 'airport_connector_12', '13s'))
George_Bush_IAH_Minneapolis_MSP = sst.Link('George_Bush_IAH_Minneapolis_MSP')
George_Bush_IAH_Minneapolis_MSP.connect((George_Bush_IAH, 'airport_connector_15', '10s'), (Minneapolis_MSP, 'airport_connector_12', '10s'))
George_Bush_IAH_Milwaukee_MKE = sst.Link('George_Bush_IAH_Milwaukee_MKE')
George_Bush_IAH_Milwaukee_MKE.connect((George_Bush_IAH, 'airport_connector_16', '9s'), (Milwaukee_MKE, 'airport_connector_12', '9s'))
George_Bush_IAH_Newark_Liberty_EWR = sst.Link('George_Bush_IAH_Newark_Liberty_EWR')
George_Bush_IAH_Newark_Liberty_EWR.connect((George_Bush_IAH, 'airport_connector_17', '13s'), (Newark_Liberty_EWR, 'airport_connector_12', '13s'))
George_Bush_IAH_Philadelphia_PHL = sst.Link('George_Bush_IAH_Philadelphia_PHL')
George_Bush_IAH_Philadelphia_PHL.connect((George_Bush_IAH, 'airport_connector_18', '13s'), (Philadelphia_PHL, 'airport_connector_12', '13s'))
George_Bush_IAH_Phoenix_PHX = sst.Link('George_Bush_IAH_Phoenix_PHX')
George_Bush_IAH_Phoenix_PHX.connect((George_Bush_IAH, 'airport_connector_19', '10s'), (Phoenix_PHX, 'airport_connector_12', '10s'))
George_Bush_IAH_Portland_PDX = sst.Link('George_Bush_IAH_Portland_PDX')
George_Bush_IAH_Portland_PDX.connect((George_Bush_IAH, 'airport_connector_20', '18s'), (Portland_PDX, 'airport_connector_12', '18s'))
George_Bush_IAH_Los_Angeles_LAX = sst.Link('George_Bush_IAH_Los_Angeles_LAX')
George_Bush_IAH_Los_Angeles_LAX.connect((George_Bush_IAH, 'airport_connector_21', '13s'), (Los_Angeles_LAX, 'airport_connector_12', '13s'))
George_Bush_IAH_New_York_LGA = sst.Link('George_Bush_IAH_New_York_LGA')
George_Bush_IAH_New_York_LGA.connect((George_Bush_IAH, 'airport_connector_22', '14s'), (New_York_LGA, 'airport_connector_12', '14s'))
George_Bush_IAH_New_York_JFK = sst.Link('George_Bush_IAH_New_York_JFK')
George_Bush_IAH_New_York_JFK.connect((George_Bush_IAH, 'airport_connector_23', '14s'), (New_York_JFK, 'airport_connector_12', '14s'))
George_Bush_IAH_Salt_Lake_City_SLC = sst.Link('George_Bush_IAH_Salt_Lake_City_SLC')
George_Bush_IAH_Salt_Lake_City_SLC.connect((George_Bush_IAH, 'airport_connector_24', '11s'), (Salt_Lake_City_SLC, 'airport_connector_12', '11s'))
George_Bush_IAH_San_Diego_SAN = sst.Link('George_Bush_IAH_San_Diego_SAN')
George_Bush_IAH_San_Diego_SAN.connect((George_Bush_IAH, 'airport_connector_25', '13s'), (San_Diego_SAN, 'airport_connector_12', '13s'))
George_Bush_IAH_San_Francisco_SFO = sst.Link('George_Bush_IAH_San_Francisco_SFO')
George_Bush_IAH_San_Francisco_SFO.connect((George_Bush_IAH, 'airport_connector_26', '16s'), (San_Francisco_SFO, 'airport_connector_12', '16s'))
George_Bush_IAH_Seattle_Tacoma_SEA = sst.Link('George_Bush_IAH_Seattle_Tacoma_SEA')
George_Bush_IAH_Seattle_Tacoma_SEA.connect((George_Bush_IAH, 'airport_connector_27', '18s'), (Seattle_Tacoma_SEA, 'airport_connector_12', '18s'))
George_Bush_IAH_Tampa_TPA = sst.Link('George_Bush_IAH_Tampa_TPA')
George_Bush_IAH_Tampa_TPA.connect((George_Bush_IAH, 'airport_connector_28', '7s'), (Tampa_TPA, 'airport_connector_12', '7s'))
Harry_Reid_LAS_Indianapolis_IND = sst.Link('Harry_Reid_LAS_Indianapolis_IND')
Harry_Reid_LAS_Indianapolis_IND.connect((Harry_Reid_LAS, 'airport_connector_13', '15s'), (Indianapolis_IND, 'airport_connector_13', '15s'))
Harry_Reid_LAS_John_Wayne_SNA = sst.Link('Harry_Reid_LAS_John_Wayne_SNA')
Harry_Reid_LAS_John_Wayne_SNA.connect((Harry_Reid_LAS, 'airport_connector_14', '2s'), (John_Wayne_SNA, 'airport_connector_13', '2s'))
Harry_Reid_LAS_Minneapolis_MSP = sst.Link('Harry_Reid_LAS_Minneapolis_MSP')
Harry_Reid_LAS_Minneapolis_MSP.connect((Harry_Reid_LAS, 'airport_connector_15', '12s'), (Minneapolis_MSP, 'airport_connector_13', '12s'))
Harry_Reid_LAS_Milwaukee_MKE = sst.Link('Harry_Reid_LAS_Milwaukee_MKE')
Harry_Reid_LAS_Milwaukee_MKE.connect((Harry_Reid_LAS, 'airport_connector_16', '15s'), (Milwaukee_MKE, 'airport_connector_13', '15s'))
Harry_Reid_LAS_Newark_Liberty_EWR = sst.Link('Harry_Reid_LAS_Newark_Liberty_EWR')
Harry_Reid_LAS_Newark_Liberty_EWR.connect((Harry_Reid_LAS, 'airport_connector_17', '22s'), (Newark_Liberty_EWR, 'airport_connector_13', '22s'))
Harry_Reid_LAS_Philadelphia_PHL = sst.Link('Harry_Reid_LAS_Philadelphia_PHL')
Harry_Reid_LAS_Philadelphia_PHL.connect((Harry_Reid_LAS, 'airport_connector_18', '21s'), (Philadelphia_PHL, 'airport_connector_13', '21s'))
Harry_Reid_LAS_Phoenix_PHX = sst.Link('Harry_Reid_LAS_Phoenix_PHX')
Harry_Reid_LAS_Phoenix_PHX.connect((Harry_Reid_LAS, 'airport_connector_19', '2s'), (Phoenix_PHX, 'airport_connector_13', '2s'))
Harry_Reid_LAS_Portland_PDX = sst.Link('Harry_Reid_LAS_Portland_PDX')
Harry_Reid_LAS_Portland_PDX.connect((Harry_Reid_LAS, 'airport_connector_20', '7s'), (Portland_PDX, 'airport_connector_13', '7s'))
Harry_Reid_LAS_Los_Angeles_LAX = sst.Link('Harry_Reid_LAS_Los_Angeles_LAX')
Harry_Reid_LAS_Los_Angeles_LAX.connect((Harry_Reid_LAS, 'airport_connector_21', '2s'), (Los_Angeles_LAX, 'airport_connector_13', '2s'))
Harry_Reid_LAS_New_York_LGA = sst.Link('Harry_Reid_LAS_New_York_LGA')
Harry_Reid_LAS_New_York_LGA.connect((Harry_Reid_LAS, 'airport_connector_22', '22s'), (New_York_LGA, 'airport_connector_13', '22s'))
Harry_Reid_LAS_New_York_JFK = sst.Link('Harry_Reid_LAS_New_York_JFK')
Harry_Reid_LAS_New_York_JFK.connect((Harry_Reid_LAS, 'airport_connector_23', '22s'), (New_York_JFK, 'airport_connector_13', '22s'))
Harry_Reid_LAS_Salt_Lake_City_SLC = sst.Link('Harry_Reid_LAS_Salt_Lake_City_SLC')
Harry_Reid_LAS_Salt_Lake_City_SLC.connect((Harry_Reid_LAS, 'airport_connector_24', '3s'), (Salt_Lake_City_SLC, 'airport_connector_13', '3s'))
Harry_Reid_LAS_San_Diego_SAN = sst.Link('Harry_Reid_LAS_San_Diego_SAN')
Harry_Reid_LAS_San_Diego_SAN.connect((Harry_Reid_LAS, 'airport_connector_25', '2s'), (San_Diego_SAN, 'airport_connector_13', '2s'))
Harry_Reid_LAS_San_Francisco_SFO = sst.Link('Harry_Reid_LAS_San_Francisco_SFO')
Harry_Reid_LAS_San_Francisco_SFO.connect((Harry_Reid_LAS, 'airport_connector_26', '4s'), (San_Francisco_SFO, 'airport_connector_13', '4s'))
Harry_Reid_LAS_Seattle_Tacoma_SEA = sst.Link('Harry_Reid_LAS_Seattle_Tacoma_SEA')
Harry_Reid_LAS_Seattle_Tacoma_SEA.connect((Harry_Reid_LAS, 'airport_connector_27', '8s'), (Seattle_Tacoma_SEA, 'airport_connector_13', '8s'))
Harry_Reid_LAS_Tampa_TPA = sst.Link('Harry_Reid_LAS_Tampa_TPA')
Harry_Reid_LAS_Tampa_TPA.connect((Harry_Reid_LAS, 'airport_connector_28', '19s'), (Tampa_TPA, 'airport_connector_13', '19s'))
Indianapolis_IND_John_Wayne_SNA = sst.Link('Indianapolis_IND_John_Wayne_SNA')
Indianapolis_IND_John_Wayne_SNA.connect((Indianapolis_IND, 'airport_connector_14', '17s'), (John_Wayne_SNA, 'airport_connector_14', '17s'))
Indianapolis_IND_Minneapolis_MSP = sst.Link('Indianapolis_IND_Minneapolis_MSP')
Indianapolis_IND_Minneapolis_MSP.connect((Indianapolis_IND, 'airport_connector_15', '5s'), (Minneapolis_MSP, 'airport_connector_14', '5s'))
Indianapolis_IND_Milwaukee_MKE = sst.Link('Indianapolis_IND_Milwaukee_MKE')
Indianapolis_IND_Milwaukee_MKE.connect((Indianapolis_IND, 'airport_connector_16', '2s'), (Milwaukee_MKE, 'airport_connector_14', '2s'))
Indianapolis_IND_Newark_Liberty_EWR = sst.Link('Indianapolis_IND_Newark_Liberty_EWR')
Indianapolis_IND_Newark_Liberty_EWR.connect((Indianapolis_IND, 'airport_connector_17', '6s'), (Newark_Liberty_EWR, 'airport_connector_14', '6s'))
Indianapolis_IND_Philadelphia_PHL = sst.Link('Indianapolis_IND_Philadelphia_PHL')
Indianapolis_IND_Philadelphia_PHL.connect((Indianapolis_IND, 'airport_connector_18', '5s'), (Philadelphia_PHL, 'airport_connector_14', '5s'))
Indianapolis_IND_Phoenix_PHX = sst.Link('Indianapolis_IND_Phoenix_PHX')
Indianapolis_IND_Phoenix_PHX.connect((Indianapolis_IND, 'airport_connector_19', '14s'), (Phoenix_PHX, 'airport_connector_14', '14s'))
Indianapolis_IND_Portland_PDX = sst.Link('Indianapolis_IND_Portland_PDX')
Indianapolis_IND_Portland_PDX.connect((Indianapolis_IND, 'airport_connector_20', '18s'), (Portland_PDX, 'airport_connector_14', '18s'))
Indianapolis_IND_Los_Angeles_LAX = sst.Link('Indianapolis_IND_Los_Angeles_LAX')
Indianapolis_IND_Los_Angeles_LAX.connect((Indianapolis_IND, 'airport_connector_21', '18s'), (Los_Angeles_LAX, 'airport_connector_14', '18s'))
Indianapolis_IND_New_York_LGA = sst.Link('Indianapolis_IND_New_York_LGA')
Indianapolis_IND_New_York_LGA.connect((Indianapolis_IND, 'airport_connector_22', '6s'), (New_York_LGA, 'airport_connector_14', '6s'))
Indianapolis_IND_New_York_JFK = sst.Link('Indianapolis_IND_New_York_JFK')
Indianapolis_IND_New_York_JFK.connect((Indianapolis_IND, 'airport_connector_23', '6s'), (New_York_JFK, 'airport_connector_14', '6s'))
Indianapolis_IND_Salt_Lake_City_SLC = sst.Link('Indianapolis_IND_Salt_Lake_City_SLC')
Indianapolis_IND_Salt_Lake_City_SLC.connect((Indianapolis_IND, 'airport_connector_24', '13s'), (Salt_Lake_City_SLC, 'airport_connector_14', '13s'))
Indianapolis_IND_San_Diego_SAN = sst.Link('Indianapolis_IND_San_Diego_SAN')
Indianapolis_IND_San_Diego_SAN.connect((Indianapolis_IND, 'airport_connector_25', '17s'), (San_Diego_SAN, 'airport_connector_14', '17s'))
Indianapolis_IND_San_Francisco_SFO = sst.Link('Indianapolis_IND_San_Francisco_SFO')
Indianapolis_IND_San_Francisco_SFO.connect((Indianapolis_IND, 'airport_connector_26', '19s'), (San_Francisco_SFO, 'airport_connector_14', '19s'))
Indianapolis_IND_Seattle_Tacoma_SEA = sst.Link('Indianapolis_IND_Seattle_Tacoma_SEA')
Indianapolis_IND_Seattle_Tacoma_SEA.connect((Indianapolis_IND, 'airport_connector_27', '18s'), (Seattle_Tacoma_SEA, 'airport_connector_14', '18s'))
Indianapolis_IND_Tampa_TPA = sst.Link('Indianapolis_IND_Tampa_TPA')
Indianapolis_IND_Tampa_TPA.connect((Indianapolis_IND, 'airport_connector_28', '8s'), (Tampa_TPA, 'airport_connector_14', '8s'))
John_Wayne_SNA_Minneapolis_MSP = sst.Link('John_Wayne_SNA_Minneapolis_MSP')
John_Wayne_SNA_Minneapolis_MSP.connect((John_Wayne_SNA, 'airport_connector_15', '15s'), (Minneapolis_MSP, 'airport_connector_15', '15s'))
John_Wayne_SNA_Milwaukee_MKE = sst.Link('John_Wayne_SNA_Milwaukee_MKE')
John_Wayne_SNA_Milwaukee_MKE.connect((John_Wayne_SNA, 'airport_connector_16', '17s'), (Milwaukee_MKE, 'airport_connector_15', '17s'))
John_Wayne_SNA_Newark_Liberty_EWR = sst.Link('John_Wayne_SNA_Newark_Liberty_EWR')
John_Wayne_SNA_Newark_Liberty_EWR.connect((John_Wayne_SNA, 'airport_connector_17', '24s'), (Newark_Liberty_EWR, 'airport_connector_15', '24s'))
John_Wayne_SNA_Philadelphia_PHL = sst.Link('John_Wayne_SNA_Philadelphia_PHL')
John_Wayne_SNA_Philadelphia_PHL.connect((John_Wayne_SNA, 'airport_connector_18', '23s'), (Philadelphia_PHL, 'airport_connector_15', '23s'))
John_Wayne_SNA_Phoenix_PHX = sst.Link('John_Wayne_SNA_Phoenix_PHX')
John_Wayne_SNA_Phoenix_PHX.connect((John_Wayne_SNA, 'airport_connector_19', '3s'), (Phoenix_PHX, 'airport_connector_15', '3s'))
John_Wayne_SNA_Portland_PDX = sst.Link('John_Wayne_SNA_Portland_PDX')
John_Wayne_SNA_Portland_PDX.connect((John_Wayne_SNA, 'airport_connector_20', '8s'), (Portland_PDX, 'airport_connector_15', '8s'))
John_Wayne_SNA_Los_Angeles_LAX = sst.Link('John_Wayne_SNA_Los_Angeles_LAX')
John_Wayne_SNA_Los_Angeles_LAX.connect((John_Wayne_SNA, 'airport_connector_21', '1s'), (Los_Angeles_LAX, 'airport_connector_15', '1s'))
John_Wayne_SNA_New_York_LGA = sst.Link('John_Wayne_SNA_New_York_LGA')
John_Wayne_SNA_New_York_LGA.connect((John_Wayne_SNA, 'airport_connector_22', '24s'), (New_York_LGA, 'airport_connector_15', '24s'))
John_Wayne_SNA_New_York_JFK = sst.Link('John_Wayne_SNA_New_York_JFK')
John_Wayne_SNA_New_York_JFK.connect((John_Wayne_SNA, 'airport_connector_23', '24s'), (New_York_JFK, 'airport_connector_15', '24s'))
John_Wayne_SNA_Salt_Lake_City_SLC = sst.Link('John_Wayne_SNA_Salt_Lake_City_SLC')
John_Wayne_SNA_Salt_Lake_City_SLC.connect((John_Wayne_SNA, 'airport_connector_24', '5s'), (Salt_Lake_City_SLC, 'airport_connector_15', '5s'))
John_Wayne_SNA_San_Diego_SAN = sst.Link('John_Wayne_SNA_San_Diego_SAN')
John_Wayne_SNA_San_Diego_SAN.connect((John_Wayne_SNA, 'airport_connector_25', '1s'), (San_Diego_SAN, 'airport_connector_15', '1s'))
John_Wayne_SNA_San_Francisco_SFO = sst.Link('John_Wayne_SNA_San_Francisco_SFO')
John_Wayne_SNA_San_Francisco_SFO.connect((John_Wayne_SNA, 'airport_connector_26', '3s'), (San_Francisco_SFO, 'airport_connector_15', '3s'))
John_Wayne_SNA_Seattle_Tacoma_SEA = sst.Link('John_Wayne_SNA_Seattle_Tacoma_SEA')
John_Wayne_SNA_Seattle_Tacoma_SEA.connect((John_Wayne_SNA, 'airport_connector_27', '9s'), (Seattle_Tacoma_SEA, 'airport_connector_15', '9s'))
John_Wayne_SNA_Tampa_TPA = sst.Link('John_Wayne_SNA_Tampa_TPA')
John_Wayne_SNA_Tampa_TPA.connect((John_Wayne_SNA, 'airport_connector_28', '21s'), (Tampa_TPA, 'airport_connector_15', '21s'))
Minneapolis_MSP_Milwaukee_MKE = sst.Link('Minneapolis_MSP_Milwaukee_MKE')
Minneapolis_MSP_Milwaukee_MKE.connect((Minneapolis_MSP, 'airport_connector_16', '2s'), (Milwaukee_MKE, 'airport_connector_16', '2s'))
Minneapolis_MSP_Newark_Liberty_EWR = sst.Link('Minneapolis_MSP_Newark_Liberty_EWR')
Minneapolis_MSP_Newark_Liberty_EWR.connect((Minneapolis_MSP, 'airport_connector_17', '10s'), (Newark_Liberty_EWR, 'airport_connector_16', '10s'))
Minneapolis_MSP_Philadelphia_PHL = sst.Link('Minneapolis_MSP_Philadelphia_PHL')
Minneapolis_MSP_Philadelphia_PHL.connect((Minneapolis_MSP, 'airport_connector_18', '9s'), (Philadelphia_PHL, 'airport_connector_16', '9s'))
Minneapolis_MSP_Phoenix_PHX = sst.Link('Minneapolis_MSP_Phoenix_PHX')
Minneapolis_MSP_Phoenix_PHX.connect((Minneapolis_MSP, 'airport_connector_19', '12s'), (Phoenix_PHX, 'airport_connector_16', '12s'))
Minneapolis_MSP_Portland_PDX = sst.Link('Minneapolis_MSP_Portland_PDX')
Minneapolis_MSP_Portland_PDX.connect((Minneapolis_MSP, 'airport_connector_20', '14s'), (Portland_PDX, 'airport_connector_16', '14s'))
Minneapolis_MSP_Los_Angeles_LAX = sst.Link('Minneapolis_MSP_Los_Angeles_LAX')
Minneapolis_MSP_Los_Angeles_LAX.connect((Minneapolis_MSP, 'airport_connector_21', '15s'), (Los_Angeles_LAX, 'airport_connector_16', '15s'))
Minneapolis_MSP_New_York_LGA = sst.Link('Minneapolis_MSP_New_York_LGA')
Minneapolis_MSP_New_York_LGA.connect((Minneapolis_MSP, 'airport_connector_22', '10s'), (New_York_LGA, 'airport_connector_16', '10s'))
Minneapolis_MSP_New_York_JFK = sst.Link('Minneapolis_MSP_New_York_JFK')
Minneapolis_MSP_New_York_JFK.connect((Minneapolis_MSP, 'airport_connector_23', '10s'), (New_York_JFK, 'airport_connector_16', '10s'))
Minneapolis_MSP_Salt_Lake_City_SLC = sst.Link('Minneapolis_MSP_Salt_Lake_City_SLC')
Minneapolis_MSP_Salt_Lake_City_SLC.connect((Minneapolis_MSP, 'airport_connector_24', '9s'), (Salt_Lake_City_SLC, 'airport_connector_16', '9s'))
Minneapolis_MSP_San_Diego_SAN = sst.Link('Minneapolis_MSP_San_Diego_SAN')
Minneapolis_MSP_San_Diego_SAN.connect((Minneapolis_MSP, 'airport_connector_25', '15s'), (San_Diego_SAN, 'airport_connector_16', '15s'))
Minneapolis_MSP_San_Francisco_SFO = sst.Link('Minneapolis_MSP_San_Francisco_SFO')
Minneapolis_MSP_San_Francisco_SFO.connect((Minneapolis_MSP, 'airport_connector_26', '15s'), (San_Francisco_SFO, 'airport_connector_16', '15s'))
Minneapolis_MSP_Seattle_Tacoma_SEA = sst.Link('Minneapolis_MSP_Seattle_Tacoma_SEA')
Minneapolis_MSP_Seattle_Tacoma_SEA.connect((Minneapolis_MSP, 'airport_connector_27', '13s'), (Seattle_Tacoma_SEA, 'airport_connector_16', '13s'))
Minneapolis_MSP_Tampa_TPA = sst.Link('Minneapolis_MSP_Tampa_TPA')
Minneapolis_MSP_Tampa_TPA.connect((Minneapolis_MSP, 'airport_connector_28', '13s'), (Tampa_TPA, 'airport_connector_16', '13s'))
Milwaukee_MKE_Newark_Liberty_EWR = sst.Link('Milwaukee_MKE_Newark_Liberty_EWR')
Milwaukee_MKE_Newark_Liberty_EWR.connect((Milwaukee_MKE, 'airport_connector_17', '7s'), (Newark_Liberty_EWR, 'airport_connector_17', '7s'))
Milwaukee_MKE_Philadelphia_PHL = sst.Link('Milwaukee_MKE_Philadelphia_PHL')
Milwaukee_MKE_Philadelphia_PHL.connect((Milwaukee_MKE, 'airport_connector_18', '6s'), (Philadelphia_PHL, 'airport_connector_17', '6s'))
Milwaukee_MKE_Phoenix_PHX = sst.Link('Milwaukee_MKE_Phoenix_PHX')
Milwaukee_MKE_Phoenix_PHX.connect((Milwaukee_MKE, 'airport_connector_19', '14s'), (Phoenix_PHX, 'airport_connector_17', '14s'))
Milwaukee_MKE_Portland_PDX = sst.Link('Milwaukee_MKE_Portland_PDX')
Milwaukee_MKE_Portland_PDX.connect((Milwaukee_MKE, 'airport_connector_20', '17s'), (Portland_PDX, 'airport_connector_17', '17s'))
Milwaukee_MKE_Los_Angeles_LAX = sst.Link('Milwaukee_MKE_Los_Angeles_LAX')
Milwaukee_MKE_Los_Angeles_LAX.connect((Milwaukee_MKE, 'airport_connector_21', '17s'), (Los_Angeles_LAX, 'airport_connector_17', '17s'))
Milwaukee_MKE_New_York_LGA = sst.Link('Milwaukee_MKE_New_York_LGA')
Milwaukee_MKE_New_York_LGA.connect((Milwaukee_MKE, 'airport_connector_22', '7s'), (New_York_LGA, 'airport_connector_17', '7s'))
Milwaukee_MKE_New_York_JFK = sst.Link('Milwaukee_MKE_New_York_JFK')
Milwaukee_MKE_New_York_JFK.connect((Milwaukee_MKE, 'airport_connector_23', '7s'), (New_York_JFK, 'airport_connector_17', '7s'))
Milwaukee_MKE_Salt_Lake_City_SLC = sst.Link('Milwaukee_MKE_Salt_Lake_City_SLC')
Milwaukee_MKE_Salt_Lake_City_SLC.connect((Milwaukee_MKE, 'airport_connector_24', '12s'), (Salt_Lake_City_SLC, 'airport_connector_17', '12s'))
Milwaukee_MKE_San_Diego_SAN = sst.Link('Milwaukee_MKE_San_Diego_SAN')
Milwaukee_MKE_San_Diego_SAN.connect((Milwaukee_MKE, 'airport_connector_25', '17s'), (San_Diego_SAN, 'airport_connector_17', '17s'))
Milwaukee_MKE_San_Francisco_SFO = sst.Link('Milwaukee_MKE_San_Francisco_SFO')
Milwaukee_MKE_San_Francisco_SFO.connect((Milwaukee_MKE, 'airport_connector_26', '18s'), (San_Francisco_SFO, 'airport_connector_17', '18s'))
Milwaukee_MKE_Seattle_Tacoma_SEA = sst.Link('Milwaukee_MKE_Seattle_Tacoma_SEA')
Milwaukee_MKE_Seattle_Tacoma_SEA.connect((Milwaukee_MKE, 'airport_connector_27', '16s'), (Seattle_Tacoma_SEA, 'airport_connector_17', '16s'))
Milwaukee_MKE_Tampa_TPA = sst.Link('Milwaukee_MKE_Tampa_TPA')
Milwaukee_MKE_Tampa_TPA.connect((Milwaukee_MKE, 'airport_connector_28', '10s'), (Tampa_TPA, 'airport_connector_17', '10s'))
Newark_Liberty_EWR_Philadelphia_PHL = sst.Link('Newark_Liberty_EWR_Philadelphia_PHL')
Newark_Liberty_EWR_Philadelphia_PHL.connect((Newark_Liberty_EWR, 'airport_connector_18', '1s'), (Philadelphia_PHL, 'airport_connector_18', '1s'))
Newark_Liberty_EWR_Phoenix_PHX = sst.Link('Newark_Liberty_EWR_Phoenix_PHX')
Newark_Liberty_EWR_Phoenix_PHX.connect((Newark_Liberty_EWR, 'airport_connector_19', '21s'), (Phoenix_PHX, 'airport_connector_18', '21s'))
Newark_Liberty_EWR_Portland_PDX = sst.Link('Newark_Liberty_EWR_Portland_PDX')
Newark_Liberty_EWR_Portland_PDX.connect((Newark_Liberty_EWR, 'airport_connector_20', '24s'), (Portland_PDX, 'airport_connector_18', '24s'))
Newark_Liberty_EWR_Los_Angeles_LAX = sst.Link('Newark_Liberty_EWR_Los_Angeles_LAX')
Newark_Liberty_EWR_Los_Angeles_LAX.connect((Newark_Liberty_EWR, 'airport_connector_21', '24s'), (Los_Angeles_LAX, 'airport_connector_18', '24s'))
Newark_Liberty_EWR_New_York_LGA = sst.Link('Newark_Liberty_EWR_New_York_LGA')
Newark_Liberty_EWR_New_York_LGA.connect((Newark_Liberty_EWR, 'airport_connector_22', '1s'), (New_York_LGA, 'airport_connector_18', '1s'))
Newark_Liberty_EWR_New_York_JFK = sst.Link('Newark_Liberty_EWR_New_York_JFK')
Newark_Liberty_EWR_New_York_JFK.connect((Newark_Liberty_EWR, 'airport_connector_23', '1s'), (New_York_JFK, 'airport_connector_18', '1s'))
Newark_Liberty_EWR_Salt_Lake_City_SLC = sst.Link('Newark_Liberty_EWR_Salt_Lake_City_SLC')
Newark_Liberty_EWR_Salt_Lake_City_SLC.connect((Newark_Liberty_EWR, 'airport_connector_24', '19s'), (Salt_Lake_City_SLC, 'airport_connector_18', '19s'))
Newark_Liberty_EWR_San_Diego_SAN = sst.Link('Newark_Liberty_EWR_San_Diego_SAN')
Newark_Liberty_EWR_San_Diego_SAN.connect((Newark_Liberty_EWR, 'airport_connector_25', '24s'), (San_Diego_SAN, 'airport_connector_18', '24s'))
Newark_Liberty_EWR_San_Francisco_SFO = sst.Link('Newark_Liberty_EWR_San_Francisco_SFO')
Newark_Liberty_EWR_San_Francisco_SFO.connect((Newark_Liberty_EWR, 'airport_connector_26', '25s'), (San_Francisco_SFO, 'airport_connector_18', '25s'))
Newark_Liberty_EWR_Seattle_Tacoma_SEA = sst.Link('Newark_Liberty_EWR_Seattle_Tacoma_SEA')
Newark_Liberty_EWR_Seattle_Tacoma_SEA.connect((Newark_Liberty_EWR, 'airport_connector_27', '24s'), (Seattle_Tacoma_SEA, 'airport_connector_18', '24s'))
Newark_Liberty_EWR_Tampa_TPA = sst.Link('Newark_Liberty_EWR_Tampa_TPA')
Newark_Liberty_EWR_Tampa_TPA.connect((Newark_Liberty_EWR, 'airport_connector_28', '9s'), (Tampa_TPA, 'airport_connector_18', '9s'))
Philadelphia_PHL_Phoenix_PHX = sst.Link('Philadelphia_PHL_Phoenix_PHX')
Philadelphia_PHL_Phoenix_PHX.connect((Philadelphia_PHL, 'airport_connector_19', '20s'), (Phoenix_PHX, 'airport_connector_19', '20s'))
Philadelphia_PHL_Portland_PDX = sst.Link('Philadelphia_PHL_Portland_PDX')
Philadelphia_PHL_Portland_PDX.connect((Philadelphia_PHL, 'airport_connector_20', '24s'), (Portland_PDX, 'airport_connector_19', '24s'))
Philadelphia_PHL_Los_Angeles_LAX = sst.Link('Philadelphia_PHL_Los_Angeles_LAX')
Philadelphia_PHL_Los_Angeles_LAX.connect((Philadelphia_PHL, 'airport_connector_21', '24s'), (Los_Angeles_LAX, 'airport_connector_19', '24s'))
Philadelphia_PHL_New_York_LGA = sst.Link('Philadelphia_PHL_New_York_LGA')
Philadelphia_PHL_New_York_LGA.connect((Philadelphia_PHL, 'airport_connector_22', '1s'), (New_York_LGA, 'airport_connector_19', '1s'))
Philadelphia_PHL_New_York_JFK = sst.Link('Philadelphia_PHL_New_York_JFK')
Philadelphia_PHL_New_York_JFK.connect((Philadelphia_PHL, 'airport_connector_23', '1s'), (New_York_JFK, 'airport_connector_19', '1s'))
Philadelphia_PHL_Salt_Lake_City_SLC = sst.Link('Philadelphia_PHL_Salt_Lake_City_SLC')
Philadelphia_PHL_Salt_Lake_City_SLC.connect((Philadelphia_PHL, 'airport_connector_24', '19s'), (Salt_Lake_City_SLC, 'airport_connector_19', '19s'))
Philadelphia_PHL_San_Diego_SAN = sst.Link('Philadelphia_PHL_San_Diego_SAN')
Philadelphia_PHL_San_Diego_SAN.connect((Philadelphia_PHL, 'airport_connector_25', '23s'), (San_Diego_SAN, 'airport_connector_19', '23s'))
Philadelphia_PHL_San_Francisco_SFO = sst.Link('Philadelphia_PHL_San_Francisco_SFO')
Philadelphia_PHL_San_Francisco_SFO.connect((Philadelphia_PHL, 'airport_connector_26', '25s'), (San_Francisco_SFO, 'airport_connector_19', '25s'))
Philadelphia_PHL_Seattle_Tacoma_SEA = sst.Link('Philadelphia_PHL_Seattle_Tacoma_SEA')
Philadelphia_PHL_Seattle_Tacoma_SEA.connect((Philadelphia_PHL, 'airport_connector_27', '23s'), (Seattle_Tacoma_SEA, 'airport_connector_19', '23s'))
Philadelphia_PHL_Tampa_TPA = sst.Link('Philadelphia_PHL_Tampa_TPA')
Philadelphia_PHL_Tampa_TPA.connect((Philadelphia_PHL, 'airport_connector_28', '9s'), (Tampa_TPA, 'airport_connector_19', '9s'))
Phoenix_PHX_Portland_PDX = sst.Link('Phoenix_PHX_Portland_PDX')
Phoenix_PHX_Portland_PDX.connect((Phoenix_PHX, 'airport_connector_20', '10s'), (Portland_PDX, 'airport_connector_20', '10s'))
Phoenix_PHX_Los_Angeles_LAX = sst.Link('Phoenix_PHX_Los_Angeles_LAX')
Phoenix_PHX_Los_Angeles_LAX.connect((Phoenix_PHX, 'airport_connector_21', '3s'), (Los_Angeles_LAX, 'airport_connector_20', '3s'))
Phoenix_PHX_New_York_LGA = sst.Link('Phoenix_PHX_New_York_LGA')
Phoenix_PHX_New_York_LGA.connect((Phoenix_PHX, 'airport_connector_22', '21s'), (New_York_LGA, 'airport_connector_20', '21s'))
Phoenix_PHX_New_York_JFK = sst.Link('Phoenix_PHX_New_York_JFK')
Phoenix_PHX_New_York_JFK.connect((Phoenix_PHX, 'airport_connector_23', '21s'), (New_York_JFK, 'airport_connector_20', '21s'))
Phoenix_PHX_Salt_Lake_City_SLC = sst.Link('Phoenix_PHX_Salt_Lake_City_SLC')
Phoenix_PHX_Salt_Lake_City_SLC.connect((Phoenix_PHX, 'airport_connector_24', '5s'), (Salt_Lake_City_SLC, 'airport_connector_20', '5s'))
Phoenix_PHX_San_Diego_SAN = sst.Link('Phoenix_PHX_San_Diego_SAN')
Phoenix_PHX_San_Diego_SAN.connect((Phoenix_PHX, 'airport_connector_25', '3s'), (San_Diego_SAN, 'airport_connector_20', '3s'))
Phoenix_PHX_San_Francisco_SFO = sst.Link('Phoenix_PHX_San_Francisco_SFO')
Phoenix_PHX_San_Francisco_SFO.connect((Phoenix_PHX, 'airport_connector_26', '6s'), (San_Francisco_SFO, 'airport_connector_20', '6s'))
Phoenix_PHX_Seattle_Tacoma_SEA = sst.Link('Phoenix_PHX_Seattle_Tacoma_SEA')
Phoenix_PHX_Seattle_Tacoma_SEA.connect((Phoenix_PHX, 'airport_connector_27', '11s'), (Seattle_Tacoma_SEA, 'airport_connector_20', '11s'))
Phoenix_PHX_Tampa_TPA = sst.Link('Phoenix_PHX_Tampa_TPA')
Phoenix_PHX_Tampa_TPA.connect((Phoenix_PHX, 'airport_connector_28', '17s'), (Tampa_TPA, 'airport_connector_20', '17s'))
Portland_PDX_Los_Angeles_LAX = sst.Link('Portland_PDX_Los_Angeles_LAX')
Portland_PDX_Los_Angeles_LAX.connect((Portland_PDX, 'airport_connector_21', '8s'), (Los_Angeles_LAX, 'airport_connector_21', '8s'))
Portland_PDX_New_York_LGA = sst.Link('Portland_PDX_New_York_LGA')
Portland_PDX_New_York_LGA.connect((Portland_PDX, 'airport_connector_22', '24s'), (New_York_LGA, 'airport_connector_21', '24s'))
Portland_PDX_New_York_JFK = sst.Link('Portland_PDX_New_York_JFK')
Portland_PDX_New_York_JFK.connect((Portland_PDX, 'airport_connector_23', '24s'), (New_York_JFK, 'airport_connector_21', '24s'))
Portland_PDX_Salt_Lake_City_SLC = sst.Link('Portland_PDX_Salt_Lake_City_SLC')
Portland_PDX_Salt_Lake_City_SLC.connect((Portland_PDX, 'airport_connector_24', '6s'), (Salt_Lake_City_SLC, 'airport_connector_21', '6s'))
Portland_PDX_San_Diego_SAN = sst.Link('Portland_PDX_San_Diego_SAN')
Portland_PDX_San_Diego_SAN.connect((Portland_PDX, 'airport_connector_25', '9s'), (San_Diego_SAN, 'airport_connector_21', '9s'))
Portland_PDX_San_Francisco_SFO = sst.Link('Portland_PDX_San_Francisco_SFO')
Portland_PDX_San_Francisco_SFO.connect((Portland_PDX, 'airport_connector_26', '5s'), (San_Francisco_SFO, 'airport_connector_21', '5s'))
Portland_PDX_Seattle_Tacoma_SEA = sst.Link('Portland_PDX_Seattle_Tacoma_SEA')
Portland_PDX_Seattle_Tacoma_SEA.connect((Portland_PDX, 'airport_connector_27', '1s'), (Seattle_Tacoma_SEA, 'airport_connector_21', '1s'))
Portland_PDX_Tampa_TPA = sst.Link('Portland_PDX_Tampa_TPA')
Portland_PDX_Tampa_TPA.connect((Portland_PDX, 'airport_connector_28', '24s'), (Tampa_TPA, 'airport_connector_21', '24s'))
Los_Angeles_LAX_New_York_LGA = sst.Link('Los_Angeles_LAX_New_York_LGA')
Los_Angeles_LAX_New_York_LGA.connect((Los_Angeles_LAX, 'airport_connector_22', '24s'), (New_York_LGA, 'airport_connector_22', '24s'))
Los_Angeles_LAX_New_York_JFK = sst.Link('Los_Angeles_LAX_New_York_JFK')
Los_Angeles_LAX_New_York_JFK.connect((Los_Angeles_LAX, 'airport_connector_23', '24s'), (New_York_JFK, 'airport_connector_22', '24s'))
Los_Angeles_LAX_Salt_Lake_City_SLC = sst.Link('Los_Angeles_LAX_Salt_Lake_City_SLC')
Los_Angeles_LAX_Salt_Lake_City_SLC.connect((Los_Angeles_LAX, 'airport_connector_24', '5s'), (Salt_Lake_City_SLC, 'airport_connector_22', '5s'))
Los_Angeles_LAX_San_Diego_SAN = sst.Link('Los_Angeles_LAX_San_Diego_SAN')
Los_Angeles_LAX_San_Diego_SAN.connect((Los_Angeles_LAX, 'airport_connector_25', '1s'), (San_Diego_SAN, 'airport_connector_22', '1s'))
Los_Angeles_LAX_San_Francisco_SFO = sst.Link('Los_Angeles_LAX_San_Francisco_SFO')
Los_Angeles_LAX_San_Francisco_SFO.connect((Los_Angeles_LAX, 'airport_connector_26', '3s'), (San_Francisco_SFO, 'airport_connector_22', '3s'))
Los_Angeles_LAX_Seattle_Tacoma_SEA = sst.Link('Los_Angeles_LAX_Seattle_Tacoma_SEA')
Los_Angeles_LAX_Seattle_Tacoma_SEA.connect((Los_Angeles_LAX, 'airport_connector_27', '9s'), (Seattle_Tacoma_SEA, 'airport_connector_22', '9s'))
Los_Angeles_LAX_Tampa_TPA = sst.Link('Los_Angeles_LAX_Tampa_TPA')
Los_Angeles_LAX_Tampa_TPA.connect((Los_Angeles_LAX, 'airport_connector_28', '21s'), (Tampa_TPA, 'airport_connector_22', '21s'))
New_York_LGA_New_York_JFK = sst.Link('New_York_LGA_New_York_JFK')
New_York_LGA_New_York_JFK.connect((New_York_LGA, 'airport_connector_23', '1s'), (New_York_JFK, 'airport_connector_23', '1s'))
New_York_LGA_Salt_Lake_City_SLC = sst.Link('New_York_LGA_Salt_Lake_City_SLC')
New_York_LGA_Salt_Lake_City_SLC.connect((New_York_LGA, 'airport_connector_24', '19s'), (Salt_Lake_City_SLC, 'airport_connector_23', '19s'))
New_York_LGA_San_Diego_SAN = sst.Link('New_York_LGA_San_Diego_SAN')
New_York_LGA_San_Diego_SAN.connect((New_York_LGA, 'airport_connector_25', '24s'), (San_Diego_SAN, 'airport_connector_23', '24s'))
New_York_LGA_San_Francisco_SFO = sst.Link('New_York_LGA_San_Francisco_SFO')
New_York_LGA_San_Francisco_SFO.connect((New_York_LGA, 'airport_connector_26', '25s'), (San_Francisco_SFO, 'airport_connector_23', '25s'))
New_York_LGA_Seattle_Tacoma_SEA = sst.Link('New_York_LGA_Seattle_Tacoma_SEA')
New_York_LGA_Seattle_Tacoma_SEA.connect((New_York_LGA, 'airport_connector_27', '24s'), (Seattle_Tacoma_SEA, 'airport_connector_23', '24s'))
New_York_LGA_Tampa_TPA = sst.Link('New_York_LGA_Tampa_TPA')
New_York_LGA_Tampa_TPA.connect((New_York_LGA, 'airport_connector_28', '10s'), (Tampa_TPA, 'airport_connector_23', '10s'))
New_York_JFK_Salt_Lake_City_SLC = sst.Link('New_York_JFK_Salt_Lake_City_SLC')
New_York_JFK_Salt_Lake_City_SLC.connect((New_York_JFK, 'airport_connector_24', '19s'), (Salt_Lake_City_SLC, 'airport_connector_24', '19s'))
New_York_JFK_San_Diego_SAN = sst.Link('New_York_JFK_San_Diego_SAN')
New_York_JFK_San_Diego_SAN.connect((New_York_JFK, 'airport_connector_25', '24s'), (San_Diego_SAN, 'airport_connector_24', '24s'))
New_York_JFK_San_Francisco_SFO = sst.Link('New_York_JFK_San_Francisco_SFO')
New_York_JFK_San_Francisco_SFO.connect((New_York_JFK, 'airport_connector_26', '25s'), (San_Francisco_SFO, 'airport_connector_24', '25s'))
New_York_JFK_Seattle_Tacoma_SEA = sst.Link('New_York_JFK_Seattle_Tacoma_SEA')
New_York_JFK_Seattle_Tacoma_SEA.connect((New_York_JFK, 'airport_connector_27', '24s'), (Seattle_Tacoma_SEA, 'airport_connector_24', '24s'))
New_York_JFK_Tampa_TPA = sst.Link('New_York_JFK_Tampa_TPA')
New_York_JFK_Tampa_TPA.connect((New_York_JFK, 'airport_connector_28', '10s'), (Tampa_TPA, 'airport_connector_24', '10s'))
Salt_Lake_City_SLC_San_Diego_SAN = sst.Link('Salt_Lake_City_SLC_San_Diego_SAN')
Salt_Lake_City_SLC_San_Diego_SAN.connect((Salt_Lake_City_SLC, 'airport_connector_25', '6s'), (San_Diego_SAN, 'airport_connector_25', '6s'))
Salt_Lake_City_SLC_San_Francisco_SFO = sst.Link('Salt_Lake_City_SLC_San_Francisco_SFO')
Salt_Lake_City_SLC_San_Francisco_SFO.connect((Salt_Lake_City_SLC, 'airport_connector_26', '5s'), (San_Francisco_SFO, 'airport_connector_25', '5s'))
Salt_Lake_City_SLC_Seattle_Tacoma_SEA = sst.Link('Salt_Lake_City_SLC_Seattle_Tacoma_SEA')
Salt_Lake_City_SLC_Seattle_Tacoma_SEA.connect((Salt_Lake_City_SLC, 'airport_connector_27', '6s'), (Seattle_Tacoma_SEA, 'airport_connector_25', '6s'))
Salt_Lake_City_SLC_Tampa_TPA = sst.Link('Salt_Lake_City_SLC_Tampa_TPA')
Salt_Lake_City_SLC_Tampa_TPA.connect((Salt_Lake_City_SLC, 'airport_connector_28', '18s'), (Tampa_TPA, 'airport_connector_25', '18s'))
San_Diego_SAN_San_Francisco_SFO = sst.Link('San_Diego_SAN_San_Francisco_SFO')
San_Diego_SAN_San_Francisco_SFO.connect((San_Diego_SAN, 'airport_connector_26', '4s'), (San_Francisco_SFO, 'airport_connector_26', '4s'))
San_Diego_SAN_Seattle_Tacoma_SEA = sst.Link('San_Diego_SAN_Seattle_Tacoma_SEA')
San_Diego_SAN_Seattle_Tacoma_SEA.connect((San_Diego_SAN, 'airport_connector_27', '10s'), (Seattle_Tacoma_SEA, 'airport_connector_26', '10s'))
San_Diego_SAN_Tampa_TPA = sst.Link('San_Diego_SAN_Tampa_TPA')
San_Diego_SAN_Tampa_TPA.connect((San_Diego_SAN, 'airport_connector_28', '20s'), (Tampa_TPA, 'airport_connector_26', '20s'))
San_Francisco_SFO_Seattle_Tacoma_SEA = sst.Link('San_Francisco_SFO_Seattle_Tacoma_SEA')
San_Francisco_SFO_Seattle_Tacoma_SEA.connect((San_Francisco_SFO, 'airport_connector_27', '6s'), (Seattle_Tacoma_SEA, 'airport_connector_27', '6s'))
San_Francisco_SFO_Tampa_TPA = sst.Link('San_Francisco_SFO_Tampa_TPA')
San_Francisco_SFO_Tampa_TPA.connect((San_Francisco_SFO, 'airport_connector_28', '23s'), (Tampa_TPA, 'airport_connector_27', '23s'))
Seattle_Tacoma_SEA_Tampa_TPA = sst.Link('Seattle_Tacoma_SEA_Tampa_TPA')
Seattle_Tacoma_SEA_Tampa_TPA.connect((Seattle_Tacoma_SEA, 'airport_connector_28', '25s'), (Tampa_TPA, 'airport_connector_28', '25s'))
